// Массив 613 НОВЫХ слов для HSK 4 (слов, которых нет в HSK 1–3)
const hsk4Words = [
    { id: 601, char: "爱好", pinyin: "àihào", translation: "хобби", example: "爱好音乐 [àihào yīnyùe] — любить музыку" },
    { id: 602, char: "爱情", pinyin: "ài qíng", translation: "любовь; чувство любви", example: "" },
    { id: 603, char: "安排", pinyin: "ānpái", translation: "налаживать; устраивать; планировать", example: "" },
    { id: 604, char: "安全", pinyin: "ānquán", translation: "безопасность; безопасный", example: "" },
    { id: 605, char: "按时", pinyin: "ànshí", translation: "вовремя; своевременно", example: "" },
    { id: 606, char: "按照", pinyin: "ànzhào", translation: "согласно; по; в соответствии с", example: "按照计划 [ànzhào jìhuà] — в соответствии с планом; по плану" },
    { id: 607, char: "包括", pinyin: "bāokuò", translation: "охватывать, включать; в том числе", example: "" },
    { id: 608, char: "保护", pinyin: "bǎohù", translation: "защищать; охранять; охрана", example: "保护国家利益 [bǎohù guójiā lìyì] — защищать интересы страны 劳动保护 [láodòng bǎohù] — охрана труда" },
    { id: 609, char: "保证", pinyin: "bǎozhèng", translation: "гарантировать; ручаться; обязываться; гарантия; залог; обязательство", example: "提出保证 [tíchū bǎozhèng] — предоставлять гарантии; давать обязательство" },
    { id: 610, char: "抱歉", pinyin: "bàoqiàn", translation: "сожалеть, выражать сожаление; к сожалению", example: "" },
    { id: 611, char: "报道", pinyin: "bàodào", translation: "сообщать, информировать", example: "据新华社报道 [jù xīnhuáshè bàodào] — по сообщениям агентства Синьхуа" },
    { id: 612, char: "报名", pinyin: "bàomíng", translation: "записаться, зарегистрироваться", example: "" },
    { id: 613, char: "倍", pinyin: "bèi", translation: "раз; крат", example: "超过一倍 [chāoguò yībèi] — превзойти в 2 раза" },
    { id: 614, char: "本来", pinyin: "běnlái", translation: "первоначальный; истинный; вообще говоря, собственно говоря", example: "" },
    { id: 615, char: "笨", pinyin: "bèn", translation: "глупый; тупой", example: "他很笨 [tā hén bèn] — он очень тупой 笨主意 [bèn zhǔyì] — глупая идея" },
    { id: 616, char: "比如", pinyin: "bǐrú", translation: "например", example: "" },
    { id: 617, char: "笔记", pinyin: "bǐjì", translation: "конспектировать; записывать; конспект, записи", example: "记笔记 [jì bǐjì] — вести конспект" },
    { id: 618, char: "毕业", pinyin: "bìyè", translation: "закончить курс; окончить", example: "毕业论文 [bìyè lùnwén] — дипломная работа 毕业证书 [bìyè zhèngshū] — диплом; аттестат" },
    { id: 619, char: "遍", pinyin: "biàn", translation: "раз; разок", example: "请再说一遍 [qǐng zài shuō yībiàn] — повторите, пожалуйста, ещё раз" },
    { id: 620, char: "标准", pinyin: "biāozhǔn", translation: "стандарт; норма; критерий; стандартный; нормативный", example: "符合标准 [fúhé biāozhǔn] — соответствовать стандарту [норме] 标准音 [biāozhǔnyīn] — нормативное [литературное] произношение" },
    { id: 621, char: "表达", pinyin: "biǎodá", translation: "выражать (напр., мысли); передавать (смысл)", example: "" },
    { id: 622, char: "表格", pinyin: "biǎogé", translation: "бланк; форма", example: "" },
    { id: 623, char: "表扬", pinyin: "biǎoyáng", translation: "отмечать, поощрять", example: "" },
    { id: 624, char: "饼干", pinyin: "bǐnggān", translation: "печенье; бисквит", example: "" },
    { id: 625, char: "并且", pinyin: "bìngqiě", translation: "к тому же; вместе с тем; и", example: "" },
    { id: 626, char: "博士", pinyin: "bóshì", translation: "доктор (наук)", example: "博士论文 [bóshì lùnwén] — докторская диссертация" },
    { id: 627, char: "不但", pinyin: "bùdàn", translation: "не только", example: "不但 …, 而且 … [bùdàn..., érqiě...] — не только…, но и…" },
    { id: 628, char: "不得不", pinyin: "bùdébù", translation: "быть вынужденным", example: "" },
    { id: 629, char: "不管", pinyin: "bùguǎn", translation: "несмотря на (то, что); независимо от того; как бы ни; будь то; кто бы ни", example: "不管是谁 [bùguǎn shì shuí] — кто бы то ни был" },
    { id: 630, char: "不过", pinyin: "bùguò", translation: "однако; впрочем", example: "他不过二十岁 [tā bùguò èrshí suì] — ему всего лишь двадцать лет" },
    { id: 631, char: "不仅", pinyin: "bùjǐn", translation: "не только", example: "" },
    { id: 632, char: "部分", pinyin: "bùfen", translation: "часть; доля", example: "" },
    { id: 633, char: "擦", pinyin: "cā", translation: "тереть; вытирать", example: "擦背 [cā bèi] — тереть спину 擦桌子 [cā zhuōzi] — вытереть стол; стереть со стола" },
    { id: 634, char: "猜", pinyin: "cāi", translation: "догадываться; угадывать", example: "猜不出 [cāibuchū] — не угадать; теряться в догадках 猜谜语 [cāi míyǔ] — разгадывать загадки" },
    { id: 635, char: "材料", pinyin: "cáiliào", translation: "материал", example: "参考材料 [cānkǎo cáiliào] — справочные материалы" },
    { id: 636, char: "参观", pinyin: "cānguān", translation: "совершать экскурсию; посещать, осматривать", example: "" },
    { id: 637, char: "差不多", pinyin: "chàbuduō", translation: "почти одинаковый, почти одно и то же", example: "" },
    { id: 638, char: "尝", pinyin: "cháng", translation: "пробовать на вкус; отведать", example: "尝尽苦头 [chángjìn kǔtou] — испить до дна чашу страданий" },
    { id: 639, char: "长城", pinyin: "chángchéng", translation: "Великая китайская стена", example: "" },
    { id: 640, char: "长江", pinyin: "chángjiāng", translation: "Чанцзян [Янцзы]", example: "" },
    { id: 641, char: "场", pinyin: "chǎng", translation: "площадь; площадка; поле", example: "红场 [hóngchǎng] — Красная площадь 会场 [huìchǎng] — место [зал] заседания" },
    { id: 642, char: "超过", pinyin: "chāoguò", translation: "обогнать; опередить", example: "" },
    { id: 643, char: "吵", pinyin: "chǎo", translation: "шуметь, галдеть", example: "别吵 ! [bié chǎo] — не шумите!" },
    { id: 644, char: "成功", pinyin: "chénggōng", translation: "успех; успешный; завершиться успехом", example: "" },
    { id: 645, char: "成熟", pinyin: "chéngshú", translation: "созреть; зрелый", example: "" },
    { id: 646, char: "成为", pinyin: "chéngwéi", translation: "стать; превратиться в", example: "" },
    { id: 647, char: "诚实", pinyin: "chéngshí", translation: "честный, правдивый; честно, правдиво", example: "" },
    { id: 648, char: "乘坐", pinyin: "chéngzuò", translation: "сидеть верхом", example: "" },
    { id: 649, char: "吃惊", pinyin: "chījīng", translation: "испугаться; перепугаться", example: "" },
    { id: 650, char: "重新", pinyin: "chóngxīn", translation: "вновь, снова; заново; пере-", example: "重新登记 [chóngxīn dēngjì] — перерегистрация; перерегистрировать" },
    { id: 651, char: "抽烟", pinyin: "chōuyān", translation: "курить; курение", example: "我不抽烟 [wǒ bù chōuyān] — я не курю; я не курящий" },
{ id: 652, char: "出差", pinyin: "chūchāi", translation: "командировка; ехать в командировку", example: "他出差去了 [tā chūchāi qùle] — он уехал в командировку" },
{ id: 653, char: "出发", pinyin: "chūfā", translation: "отправиться; выступить", example: "" },
{ id: 654, char: "出生", pinyin: "chūshēng", translation: "родиться; появиться на свет", example: "出生地 [chūshēngdì] — место рождения 出生率 [chūshēnglǚ] — рождаемость" },
{ id: 655, char: "传真", pinyin: "chuánzhēn", translation: "факс", example: "传真机 [chuánzhēnjī] — факсимильный аппарат 发传真 [fá chuánzhēn] — послать факс" },
{ id: 656, char: "窗户", pinyin: "chuānghu", translation: "окно", example: "" },
{ id: 657, char: "词典", pinyin: "cídiǎn", translation: "словарь", example: "双语词典 [shuāngyǔ cídiǎn] — двуязычный словарь" },
{ id: 658, char: "从来", pinyin: "cónglái", translation: "всегда; (с последующим отрицанием) никогда", example: "我从来没有见过他 [wǒ cónglái méiyǒu jiànguo tā] — я никогда (раньше) не видел его" },
{ id: 659, char: "粗心", pinyin: "cūxīn", translation: "небрежный; небрежно; невнимательно", example: "" },
{ id: 660, char: "答案", pinyin: "dá'àn", translation: "ответ; решение", example: "" },
{ id: 661, char: "打扮", pinyin: "dǎban", translation: "наряд, одежда; наружность, внешний облик", example: "" },
{ id: 662, char: "打扰", pinyin: "dǎrǎo", translation: "тревожить, беспокоить", example: "" },
{ id: 663, char: "打印", pinyin: "dǎyìn", translation: "печатать; ставить печать; штемпелевать", example: "" },
{ id: 664, char: "打折", pinyin: "dǎzhé", translation: "сделать скидку", example: "打八折 сделать скидку в 20%" },
{ id: 665, char: "打针", pinyin: "dǎzhēn", translation: "сделать укол", example: "" },
{ id: 666, char: "大概", pinyin: "dàgài", translation: "вероятно; наверное; в общих чертах; приблизительно", example: "" },
{ id: 667, char: "大使馆", pinyin: "dàshǐguǎn", translation: "посольство", example: "" },
{ id: 668, char: "大约", pinyin: "dàyuē", translation: "приблизительно; около", example: "" },
{ id: 669, char: "戴", pinyin: "dài", translation: "носить; надевать (головной убор, перчатки, украшения и т.п.)", example: "戴眼镜 [dài yǎnjìng] — носить [надеть] очки" },
{ id: 670, char: "代表", pinyin: "dàibiǎo", translation: "представитель; делегат; депутат", example: "" },
{ id: 671, char: "代替", pinyin: "dàitì", translation: "заменять; вместо, за", example: "" },
{ id: 672, char: "大夫", pinyin: "dàifu", translation: "доктор; врач", example: "" },
{ id: 673, char: "当", pinyin: "dāng", translation: "быть, являться; становиться кем-либо", example: "当证人 [dāng zhèngrén] — быть свидетелем; выступать в качестве свидетеля 当兵 [dāngbīng] — быть солдатом; служить в армии" },
{ id: 674, char: "当地", pinyin: "dāngdì", translation: "данное место; местный", example: "当地时间 [dāngdì shíjiān] — местное время" },
{ id: 675, char: "当时", pinyin: "dàngshí", translation: "сейчас же, тут же, немедленно", example: "" },
{ id: 676, char: "刀", pinyin: "dāo", translation: "нож; меч; бритва; резец", example: "菜刀 [càidāo] — кухонный нож" },
{ id: 677, char: "导游", pinyin: "dǎoyóu", translation: "гид; экскурсовод", example: "导游图 [dǎoyóutú] — путеводитель; туристическая карта" },
{ id: 678, char: "到处", pinyin: "dàochù", translation: "везде; повсюду", example: "" },
{ id: 679, char: "到底", pinyin: "dàodǐ", translation: "в конце концов, в конечном счёте, всё-таки", example: "" },
{ id: 680, char: "道歉", pinyin: "dàoqiàn", translation: "принести извинения; извиниться", example: "" },
{ id: 681, char: "得意", pinyin: "déyì", translation: "довольный; быть довольным; самодовольный", example: "" },
{ id: 682, char: "得", pinyin: "děi", translation: "должно, следует; необходимо", example: "我得去看看 [wǒ děi qù kànkan] — я должен пойти посмотреть" },
{ id: 683, char: "等", pinyin: "děng", translation: "сорт; класс; разряд; качество; степень", example: "头等货 [tóuděng huò] — товар высшего сорта; первоклассный товар" },
{ id: 684, char: "底", pinyin: "dǐ", translation: "дно; низ; нижний; конец", example: "海底 [hǎidǐ] — дно моря 月底 [yuèdǐ] — конец месяца" },
{ id: 685, char: "地球", pinyin: "dìqiú", translation: "земной шар; Земля", example: "" },
{ id: 686, char: "地址", pinyin: "dìzhǐ", translation: "адрес", example: "" },
{ id: 687, char: "掉", pinyin: "diào", translation: "падать; выпадать; ронять; терять", example: "从马上掉下来 [cóng mǎshang diàoxialai] — упасть с лошади 我掉了钱包 [wǒ diàole qiánbāo] — я потерял кошелёк" },
{ id: 688, char: "调查", pinyin: "diàochá", translation: "обследовать; обследование", example: "人口调查 [rénkǒu diàochá] — перепись населения" },
{ id: 689, char: "丢", pinyin: "diū", translation: "потерять; утратить", example: "我丢了钱 [wǒ diūle qián] — я потерял деньги" },
{ id: 690, char: "动作", pinyin: "dòngzuò", translation: "движение; телодвижение", example: "" },
{ id: 691, char: "堵车", pinyin: "dǔchē", translation: "пробка, затор", example: "" },
{ id: 692, char: "肚子", pinyin: "dùzi", translation: "живот, брюхо", example: "肚子痛 [dùzi tòng] — живот болит" },
{ id: 693, char: "断", pinyin: "duàn", translation: "перерезать; разорвать(ся); переломить(ся)", example: "筷子断了 [kuàizi duànle] — палочка (для еды) переломилась 断烟 [duàn yān] — бросить курить" },
{ id: 694, char: "对话", pinyin: "duìhuà", translation: "диалог", example: "" },
{ id: 695, char: "对面", pinyin: "duìmiàn", translation: "напротив; против", example: "" },
{ id: 696, char: "顿", pinyin: "dùn", translation: "сч. сл. для приёмов пищи; раз", example: "一天吃三顿饭 [yītiān chī sāndùn fàn] — есть три раза в день" },
{ id: 697, char: "多么", pinyin: "duōme", translation: "так, до такой степени; насколько же…!", example: "" },
{ id: 698, char: "朵", pinyin: "duǒ", translation: "цветок", example: "一朵花 [yīduǒ huā] — один цветок" },
{ id: 699, char: "而", pinyin: "ér", translation: "и; да; к тому же; а; но", example: "聪明而勇敢 [cōngming ér yǒnggǎn] — умный и отважный 他要来而没有来 [tā yào lái ér méiyǒu lái] — он хотел приехать, но не приехал" },
{ id: 700, char: "儿童", pinyin: "értóng", translation: "дети; ребята; детский", example: "" },
{ id: 701, char: "耳朵", pinyin: "ěrduo", translation: "ухо", example: "" },
{ id: 702, char: "发", pinyin: "fā", translation: "выпускать; выдавать; отправлять", example: "发光 [fāguāng] — испускать свет; светиться; блестеть 发 电报 [fā diànbào] — послать телеграмму" },
{ id: 703, char: "发生", pinyin: "fāshēng", translation: "возникнуть; случиться; произойти; возникновение; появление", example: "发生了误会 [fāshēngle wùhuì] — произошло недоразумение" },
{ id: 704, char: "发展", pinyin: "fāzhǎn", translation: "развивать(ся); развитие", example: "发展新党员 [fāzhǎn xīn dǎngyuán] — принимать новых членов партии" },
{ id: 705, char: "法律", pinyin: "fǎlǜ", translation: "закон; право; правовой; юридический", example: "妇女法律地位 [fùnǚ fǎlǜ dìwèi] — правовое положение женщины (в обществе)" },
{ id: 706, char: "翻译", pinyin: "fānyì", translation: "переводить; перевод", example: "" },
{ id: 707, char: "烦恼", pinyin: "fánnǎo", translation: "быть удручённым; огорчения; неприятности", example: "" },
{ id: 708, char: "反对", pinyin: "fǎnduì", translation: "возражать; противодействовать; против", example: "" },
{ id: 709, char: "反映", pinyin: "fǎnyìng", translation: "отображать, отражать; отображение, отражение", example: "" },
{ id: 710, char: "范围", pinyin: "fànwéi", translation: "сфера; пределы, рамки, границы", example: "势力范围 [shìlì fànwéi] — сфера влияния" },
{ id: 711, char: "方法", pinyin: "fāngfǎ", translation: "метод, способ; средство; приём", example: "方法论 [fāngfǎlùn] — методология" },
{ id: 712, char: "方面", pinyin: "fāngmiàn", translation: "сторона", example: "一方面 [yī fāngmiàn] — одна сторона; с одной стороны" },
{ id: 713, char: "方向", pinyin: "fāngxiàng", translation: "направление; курс", example: "" },
{ id: 714, char: "访问", pinyin: "fǎngwèn", translation: "наносить визит; навещать; посещать; визит", example: "访问朋友 [fǎngwèn péngyou] — навестить друга 作正式访问 [zuò zhèngshì fǎngwèn] — посетить с официальным визитом" },
{ id: 715, char: "放弃", pinyin: "fàngqì", translation: "отказаться, отбросить; оставить; утратить", example: "放弃希望 [fàngqì xīwàng] — оставить надежды 放弃原则 [fàngqì yuánzé] — отказаться от принципов" },
{ id: 716, char: "放暑假", pinyin: "fàngshǔjià", translation: "идти на летние каникулы", example: "" },
{ id: 717, char: "份", pinyin: "fèn", translation: "часть; пай; доля; порция", example: "一份面包 [yīfèn miànbāo] — порция хлеба" },
{ id: 718, char: "丰富", pinyin: "fēngfù", translation: "богатый, обильный; обилие", example: "" },
{ id: 719, char: "风景", pinyin: "fēngjǐng", translation: "вид, пейзаж, ландшафт", example: "风景画 [fēngjǐnghuà] — пейзаж" },
{ id: 720, char: "否则", pinyin: "fǒuzé", translation: "в противном случае; иначе", example: "" },
{ id: 721, char: "符合", pinyin: "fúhé", translation: "соответствовать; совпадать; отвечать чему-либо", example: "符合原则 [fúhé yuánzé] — соответствовать принципам 符合原文 [fúhé yuánwén] — совпадать с оригиналом" },
{ id: 722, char: "父亲", pinyin: "fùqīn", translation: "отец", example: "" },
{ id: 723, char: "复印", pinyin: "fùyìn", translation: "размножать; копировать", example: "复印机 [fùyìnjī] — множительный аппарат; ксерокс" },
{ id: 724, char: "复杂", pinyin: "fùzá", translation: "сложный", example: "" },
{ id: 725, char: "负责", pinyin: "fùzé", translation: "нести ответственность; отвечать за что-либо; ответственный", example: "" },
{ id: 726, char: "改变", pinyin: "gǎibiàn", translation: "изменять, переменять; преобразовывать", example: "" },
{ id: 727, char: "干杯", pinyin: "gānbēi", translation: "выпить до капли, осушить бокал; пей до дна!", example: "" },
{ id: 728, char: "干燥", pinyin: "gānzào", translation: "сухой; засушливый", example: "" },
{ id: 729, char: "感动", pinyin: "gǎndòng", translation: "растрогаться, расчувствоваться", example: "" },
{ id: 730, char: "感觉", pinyin: "gǎnjué", translation: "чувство, ощущение; чувствовать, ощущать", example: "感觉器官 [gǎnjué qìguān] — органы чувств" },
{ id: 731, char: "感情", pinyin: "gǎnqíng", translation: "чувство; эмоция", example: "动感情 [dòng gǎnqíng] — поддаваться эмоциям" },
{ id: 732, char: "感谢", pinyin: "gǎnxiè", translation: "благодарить; благодарность", example: "" },
{ id: 733, char: "干", pinyin: "gàn", translation: "делать; заниматься (делами)", example: "干工作 [gàn gōngzuò] — заниматься какой-либо работой, работать 干事情 [gàn shìqing] — заниматься делами" },
{ id: 734, char: "刚刚", pinyin: "gānggāng", translation: "только что, только-только", example: "" },
{ id: 735, char: "高级", pinyin: "gāojí", translation: "высший (напр., о руководстве); высокосортный; высококачественный", example: "" },
{ id: 736, char: "各", pinyin: "gè", translation: "каждый; всякий; все; различный", example: "各持己见 [gè chí jǐ jiàn] — каждый остался при своём мнении 我国各族人民 [wǒguó gè zú rénmín] — (все) народы нашей страны" },
{ id: 737, char: "个子", pinyin: "gèzi", translation: "рост, комплекция", example: "" },
{ id: 738, char: "跟", pinyin: "gēn", translation: "и; с; за; у", example: "我跟他是弟兄 [wǒ gēn tā shì dìxiong] — я и он — братья 你跟他说了没有 ? [nǐ gēn tā shuōle méiyǒu] — ты говорил с ним?" },
{ id: 739, char: "公里", pinyin: "gōnglǐ", translation: "километр", example: "" },
{ id: 740, char: "工具", pinyin: "gōngjù", translation: "инструмент; орудие (производства)", example: "" },
{ id: 741, char: "工资", pinyin: "gōngzī", translation: "заработная плата", example: "" },
{ id: 742, char: "共同", pinyin: "gòngtóng", translation: "совместный, общий; совместно, сообща", example: "共同市场 [gòngtóng shìcháng] — общий рынок" },
{ id: 743, char: "够", pinyin: "gòu", translation: "достаточно, довольно; хватает", example: "钱不够 [qián bù gòu] — не хватает денег 够了 ! [gòule] — хватит!, довольно!" },
{ id: 744, char: "购物", pinyin: "gòuwù", translation: "торговый, коммерческий", example: "" },
{ id: 745, char: "孤单", pinyin: "gūdān", translation: "одинокий; одиночество", example: "" },
{ id: 746, char: "估计", pinyin: "gūjì", translation: "оценивать; прикидывать; оценка", example: "" },
{ id: 747, char: "鼓励", pinyin: "gǔlì", translation: "воодушевлять; ободрять; поощрять", example: "" },
{ id: 748, char: "鼓掌", pinyin: "gǔzhǎng", translation: "аплодировать; аплодисменты", example: "" },
{ id: 749, char: "顾客", pinyin: "gùkè", translation: "покупатель; клиент", example: "顾客之上 [gùkè zhīshàng] — покупатель всегда прав" },
{ id: 750, char: "故意", pinyin: "gùyì", translation: "намеренно; умышленно; нарочно", example: "" },
{ id: 751, char: "挂", pinyin: "guà", translation: "вешать; вывешивать; висеть; висячий", example: "挂窗帘 [guà chuānglián] — повесить оконные занавески 挂旗 [guàqí] — вывесить флаг" },
{ id: 752, char: "关键", pinyin: "guānjiàn", translation: "решающий фактор; ключ; ключевой; решающий", example: "关键问题 [guānjiàn wèntí] — ключевой вопрос" },
{ id: 753, char: "观众", pinyin: "guānzhòng", translation: "зрители; публика", example: "" },
{ id: 754, char: "管理", pinyin: "guǎnlǐ", translation: "управлять; заведовать; ведать; управление", example: "田间管理 [tiánjiān guǎnlǐ] — уход за посевами" },
{ id: 755, char: "光", pinyin: "guāng", translation: "свет; излучение; блеск; сияние", example: "灯光 [dēngguāng] — свет лампы [фонаря] 日光 [rìguāng] — солнечный свет" },
{ id: 756, char: "广播", pinyin: "guǎngbō", translation: "радиовещание; передавать по радио", example: "广播电台 [guǎngbō diàntái] — (широковещательная) радиостанция" },
{ id: 757, char: "广告", pinyin: "guǎnggào", translation: "объявление; реклама; афиша", example: "作广告 [zuò guǎnggào] — рекламировать" },
{ id: 758, char: "逛", pinyin: "guàng", translation: "прогуливаться, прохаживаться; гулять; шоппинг", example: "逛街头 [guàng jiētóu] — прогуливаться по улицам 闲逛 [xiánguàng] — слоняться без дела, шататься" },
{ id: 759, char: "规定", pinyin: "guīdìng", translation: "устанавливать; определять; предусматривать", example: "" },
{ id: 760, char: "国际", pinyin: "guójì", translation: "международный; интернациональный", example: "国际形势 [guójì xíngshì] — международное положение; международная обстановка" },
{ id: 761, char: "果然", pinyin: "guǒrán", translation: "действительно, в самом деле", example: "" },
{ id: 762, char: "过", pinyin: "guō", translation: "превосходить, превышать; чересчур, слишком", example: "" },
{ id: 763, char: "过程", pinyin: "guòchéng", translation: "процесс; ход (дела)", example: "" },
{ id: 764, char: "海洋", pinyin: "hǎiyáng", translation: "моря и океаны; морской", example: "海洋法 [hǎiyángfǎ] — морское право" },
{ id: 765, char: "寒假", pinyin: "hánjià", translation: "зимние каникулы", example: "" },
{ id: 766, char: "汗", pinyin: "hàn", translation: "пот; испарина", example: "出汗 [chūhàn] — потеть 浑身是汗 [húnshēn shì hàn] — весь в поту" },
{ id: 767, char: "航班", pinyin: "hángbān", translation: "рейс; номер рейса", example: "" },
{ id: 768, char: "好处", pinyin: "hǎochu", translation: "польза, выгода, толк, прок, добро", example: "好处费 [hǎochufèi] — чаевые" },
{ id: 769, char: "好像", pinyin: "hǎoxiàng", translation: "подобный; как будто; словно [бы]; похоже, что…", example: "" },
{ id: 770, char: "号码", pinyin: "hàomǎ", translation: "номер", example: "" },
{ id: 771, char: "河", pinyin: "hé", translation: "река; речной", example: "过河 [guòhé] — переправиться через реку" },
{ id: 772, char: "合格", pinyin: "hégé", translation: "соответствовать стандарту [норме]; отвечать требованиям", example: "合格证 [hégézhèng] — сертификат качества" },
{ id: 773, char: "合适", pinyin: "héshì", translation: "подходить; подходящий; в самый раз", example: "" },
{ id: 774, char: "盒子", pinyin: "hézi", translation: "ящик; коробка", example: "盒子带 [hézidài] — кассета (напр., магнитофонная)" },
{ id: 775, char: "猴子", pinyin: "hóuzi", translation: "обезьяна", example: "" },
{ id: 776, char: "厚", pinyin: "hòu", translation: "толстый (о плоских предметах)", example: "厚纸 [hòuzhǐ] — толстая бумага 厚木版 [hòu mùbǎn] — толстая доска" },
{ id: 777, char: "后悔", pinyin: "hòuhuǐ", translation: "раскаиваться; сожалеть; раскаяние", example: "" },
{ id: 778, char: "后来", pinyin: "hòulái", translation: "потом, впоследствии, затем", example: "" },
{ id: 779, char: "忽然", pinyin: "hūrán", translation: "вдруг, внезапно, неожиданно", example: "" },
{ id: 780, char: "护士", pinyin: "hùshi", translation: "медицинская сестра, медсестра", example: "" },
{ id: 781, char: "护照", pinyin: "hùzhào", translation: "паспорт", example: "出国护照 [chūguó hùzhào] — заграничный паспорт" },
{ id: 782, char: "互相", pinyin: "hùxiāng", translation: "взаимно; взаимный; взаимо-", example: "互相帮助 [hùxiāng bāngzhù] — взаимопомощь; взаимовыручка" },
{ id: 783, char: "怀疑", pinyin: "huáiyí", translation: "сомневаться; сомнение", example: "" },
{ id: 784, char: "坏", pinyin: "huài", translation: "плохой; негодный; дурной; испортиться; сломаться", example: "坏人 [huàirén] — плохой [дурной] человек 肉坏了 [ròu huàile] — мясо испортилось" },
{ id: 785, char: "回忆", pinyin: "huíyì", translation: "вспоминать; воспоминание", example: "回忆录 [huíyìlù] — мемуары; воспоминания" },
{ id: 786, char: "活动", pinyin: "huódòng", translation: "действовать; действие; деятельность; мероприятие", example: "" },
{ id: 787, char: "活泼", pinyin: "huópo", translation: "живой; бойкий; подвижный", example: "" },
{ id: 788, char: "火", pinyin: "huǒ", translation: "огонь; пламя", example: "点火 [diǎn huǒ] — зажечь огонь" },
{ id: 789, char: "获得", pinyin: "huòdé", translation: "получить; достигнуть; добиться", example: "获得丰收 [huòdé fēngshōu] , — получить [собрать] богатый урожай" },
{ id: 790, char: "基础", pinyin: "jīchǔ", translation: "основа; база; фундамент; устои", example: "基础工业 [jīchǔ gōngyè] — ключевые отрасли промышленности 物质基础 [wùzhì jīchǔ] — материальная база" },
{ id: 791, char: "激动", pinyin: "jīdòng", translation: "возбуждать; волновать; зажигать", example: "" },
{ id: 792, char: "几乎", pinyin: "jīhū", translation: "почти; почти что; едва не", example: "" },
{ id: 793, char: "积极", pinyin: "jījí", translation: "активный; активно", example: "" },
{ id: 794, char: "积累", pinyin: "jīlěi", translation: "накапливать, копить, скапливать", example: "" },
{ id: 795, char: "极其", pinyin: "jíqí", translation: "чрезвычайно; крайне; исключительно", example: "" },
{ id: 796, char: "集合", pinyin: "jíhé", translation: "собирать(ся); сосредоточивать(ся)", example: "集合点 [jíhédiǎn] — место сбора" },
{ id: 797, char: "及时", pinyin: "jíshí", translation: "вовремя; своевременно", example: "" },
{ id: 798, char: "即使", pinyin: "jíshǐ", translation: "пусть (даже); если даже; даже если", example: "即使 … 也 … [jíshǐ... yě...] — пусть даже…, всё равно…" },
{ id: 799, char: "寄", pinyin: "jì", translation: "отправлять; посылать", example: "寄信 [jìxìn] — послать [отправить] письмо" },
{ id: 800, char: "记者", pinyin: "jìzhě", translation: "корреспондент; репортёр; журналист", example: "记者招待会 [jìzhě zhāodàihuì] — пресс-конференция" },
{ id: 801, char: "计划", pinyin: "jìhuà", translation: "план; планировать; плановый", example: "五年计划 [wǔnián jìhuà] — пятилетний план; пятилетка 订计划 [dìng jìhuà] — составлять план" },
{ id: 802, char: "既然", pinyin: "jìrán", translation: "раз (уж); поскольку", example: "" },
{ id: 803, char: "技术", pinyin: "jìshù", translation: "техника; технология", example: "高技术 [gāo jìshù] — высокая технология" },
{ id: 804, char: "继续", pinyin: "jìxù", translation: "продолжать(ся); продолжение", example: "继续工作 [jìxù gōngzuò] — продолжать работу" },
{ id: 805, char: "家具", pinyin: "jiāju", translation: "мебель; утварь", example: "" },
{ id: 806, char: "加班", pinyin: "jiābān", translation: "работать сверхурочно; сверхурочная работа", example: "" },
{ id: 807, char: "加油站", pinyin: "jiāyóuzhàn", translation: "бензозаправочная станция; бензоколонка", example: "" },
{ id: 808, char: "假", pinyin: "jiǎ", translation: "ложный; фальшивый; поддельный; фиктивный; притворный; лже-; псевдо-", example: "假科学 [jiǎ kēxué] — лженаука 假文件 [jiǎ wénjiàn] — поддельный [фальшивый] документ" },
{ id: 809, char: "价格", pinyin: "jiàgé", translation: "цена", example: "" },
{ id: 810, char: "坚持", pinyin: "jiānchí", translation: "твёрдо придерживаться; твёрдо стоять на чём-либо; отстаивать", example: "坚持原则 [jiānchí yuánzé] — твёрдо придерживаться принципов 坚持学习 [jiānchí xuéxí] — упорно учиться" },
{ id: 811, char: "减肥", pinyin: "jiǎnféi", translation: "худеть; похудание", example: "减肥热 [jiǎnféirè] — мода на похудание" },
{ id: 812, char: "减少", pinyin: "jiǎnshǎo", translation: "уменьшать; сокращать", example: "" },
{ id: 813, char: "将来", pinyin: "jiānglái", translation: "будущий; в будущем; будущее", example: "" },
{ id: 814, char: "奖金", pinyin: "jiǎngjīn", translation: "денежная награда; премия; премиальные", example: "" },
{ id: 815, char: "降低", pinyin: "jiàngdī", translation: "снизить(ся); понизить(ся); снижение; понижение", example: "" },
{ id: 816, char: "交", pinyin: "jiāo", translation: "сдавать; отдавать; водить знакомство", example: "交考卷 [jiāo kǎojuàn] — сдать экзаменационную работу 交朋友 [jiāo péngyou] — водить дружбу; дружить; подружиться" },
{ id: 817, char: "交流", pinyin: "jiāoliú", translation: "обмениваться (напр., опытом); переменный", example: "交流电 [jiāoliúdiàn] — переменный ток" },
{ id: 818, char: "交通", pinyin: "jiāotōng", translation: "связь; сообщение; коммуникации; пути сообщения", example: "交通工具 [jiāotōng gōngjù] — средства транспорта [связи]" },
{ id: 819, char: "骄傲", pinyin: "jiāo'ào", translation: "гордиться, зазнаваться; задирать нос; зазнайство; высокомерие", example: "" },
{ id: 820, char: "饺子", pinyin: "jiǎozi", translation: "пельмени", example: "" },
{ id: 821, char: "教授", pinyin: "jiàoshòu", translation: "профессор", example: "" },
{ id: 822, char: "教育", pinyin: "jiàoyù", translation: "просвещение, образование", example: "高等教育 [gāoděng jiàoyù] — высшее образование 义务教育 [yìwù jiàoyù] — обязательное обучение" },
{ id: 823, char: "接受", pinyin: "jiēshòu", translation: "принимать, получать", example: "" },
{ id: 824, char: "结果", pinyin: "jiéguǒ", translation: "результат, итог; в результате, в итоге; приносить плоды, плодоносить", example: "" },
{ id: 825, char: "节约", pinyin: "jiéyuē", translation: "экономить; беречь; экономия; бережливость", example: "" },
{ id: 826, char: "解释", pinyin: "jiěshì", translation: "объяснять, разъяснять; толковать; толкование", example: "" },
{ id: 827, char: "借", pinyin: "jiè", translation: "брать взаймы [в пользование]; брать в долг; занимать", example: "借钱 [jièqián] — занимать деньги 借书 [jièshū] — брать книги (напр., в библиотеке)" },
{ id: 828, char: "尽管", pinyin: "jǐnguǎn", translation: "смело; прямо; хотя (и); несмотря на; пусть (даже)", example: "" },
{ id: 829, char: "紧张", pinyin: "jǐnzhāng", translation: "напрягать(ся); напряжение; взволнованность", example: "紧张局势 [jǐnzhāng júshì] — напряжённая обстановка; напряжённость" },
{ id: 830, char: "进行", pinyin: "jìnxíng", translation: "проводить; осуществлять; ход; продвижение", example: "" },
{ id: 831, char: "禁止", pinyin: "jìnzhǐ", translation: "запрещать; воспрещать; запрещение, запрет", example: "禁止吸烟 [jìnzhǐ xīyān] — курить воспрещается" },
{ id: 832, char: "精彩", pinyin: "jīngcǎi", translation: "замечательный; интересный; эффектный", example: "" },
{ id: 833, char: "精神", pinyin: "jīngshén", translation: "дух; духовный; моральный; нравственный", example: "精神食粮 [jīngshén shíliáng] — духовная пища 精神文明 [jīngshén wénmíng] — духовная культура" },
{ id: 834, char: "经济", pinyin: "jīngjì", translation: "экономика; хозяйство; экономический; хозяйственный", example: "经济情况 [jīngjì qíngkuàng] — материальное положение" },
{ id: 835, char: "经历", pinyin: "jīnglì", translation: "испытать, пережить; пережитое", example: "" },
{ id: 836, char: "经验", pinyin: "jīngyàn", translation: "опыт", example: "交流经验 [jiāoliú jīngyàn] — обмениваться опытом" },
{ id: 837, char: "京剧", pinyin: "jīngjù", translation: "пекинская музыкальная драма", example: "" },
{ id: 838, char: "警察", pinyin: "jǐngchá", translation: "полиция; полицейский", example: "" },
{ id: 839, char: "竟然", pinyin: "jìngrán", translation: "в конце концов, в итоге; оказываться", example: "" },
{ id: 840, char: "竞争", pinyin: "jìngzhēng", translation: "конкурировать; соперничать; конкуренция", example: "竞争力 [jìngzhēnglì] — конкурентоспособность 竞争者 [jìngzhēngzhě] — конкурент" },
{ id: 841, char: "镜子", pinyin: "jìngzi", translation: "зеркало", example: "" },
{ id: 842, char: "究竟", pinyin: "jiūjìng", translation: "в конце концов, в конечном счёте; всё-таки", example: "" },
{ id: 843, char: "举办", pinyin: "jǔbàn", translation: "создать; организовать; основать", example: "举办展览会 [jǔbàn zhǎnlǎnhuì] — организовать выставку" },
{ id: 844, char: "拒绝", pinyin: "jùjué", translation: "отказываться; отвергать", example: "" },
{ id: 845, char: "距离", pinyin: "jùlí", translation: "отстоять от; расстояние; дистанция", example: "短距离赛跑 [duǎn jùlí sàipǎo] — бег на короткую дистанцию" },
{ id: 846, char: "开玩笑", pinyin: "kāi wánxiào", translation: "шутить; подшучивать; разыгрывать", example: "" },
{ id: 847, char: "看法", pinyin: "kànfǎ", translation: "точка зрения; подход; взгляд; мнение", example: "" },
{ id: 848, char: "考虑", pinyin: "kǎolǜ", translation: "обдумывать; взвешивать; учитывать, принимать во внимание", example: "" },
{ id: 849, char: "棵", pinyin: "kē", translation: "сч. сл. для деревьев", example: "一棵树 [yīkē shù] — одно дерево" },
{ id: 850, char: "科学", pinyin: "kēxué", translation: "наука; научный", example: "" },
{ id: 851, char: "咳嗽", pinyin: "késou", translation: "кашлять; кашель", example: "" },
{ id: 852, char: "可怜", pinyin: "kělián", translation: "жалкий; ничтожный; жалеть; сжалиться", example: "" },
{ id: 853, char: "可是", pinyin: "kěshì", translation: "а, но, однако; впрочем", example: "" },
{ id: 854, char: "可惜", pinyin: "kěxī", translation: "к сожалению; жаль; достойный сожаления", example: "" },
{ id: 855, char: "肯定", pinyin: "kěndìng", translation: "утвердительный; положительный; несомненно, безусловно", example: "" },
{ id: 856, char: "空气", pinyin: "kōngqì", translation: "воздух, атмосфера", example: "" },
{ id: 857, char: "恐怕", pinyin: "kǒngpà", translation: "бояться, опасаться", example: "" },
{ id: 858, char: "苦", pinyin: "kǔ", translation: "горький; горечь; тяжёлый", example: "苦味 [kǔwèi] — горький вкус; горечь 吃苦 [chīkǔ] — переносить невзгоды" },
{ id: 859, char: "宽", pinyin: "kuān", translation: "широкий; просторный; ширина", example: "宽街道 [kuān jiēdào] — широкие улицы" },
{ id: 860, char: "困", pinyin: "kùn", translation: "утомиться, устать", example: "孩子困了 [háizi kùnle] — ребёнок устал" },
{ id: 861, char: "困难", pinyin: "kùnnan", translation: "трудность; трудный, тяжёлый", example: "" },
{ id: 862, char: "扩大", pinyin: "kuòdà", translation: "увеличивать; расширять; расширенный", example: "" },
{ id: 863, char: "拉", pinyin: "lā", translation: "тянуть, тащить; растягивать; вытягивать", example: "拉车 [lāchē] — тащить тележку" },
{ id: 864, char: "垃圾桶", pinyin: "lājītǒng", translation: "мусорное ведро", example: "" },
{ id: 865, char: "辣", pinyin: "là", translation: "горький; острый", example: "口甜心辣 [kǒutián xīnlà] — мягко стелет, да жёстко спать" },
{ id: 866, char: "来不及", pinyin: "láibují", translation: "не успеть", example: "" },
{ id: 867, char: "来得及", pinyin: "láidejí", translation: "успеть", example: "" },
{ id: 868, char: "懒", pinyin: "lǎn", translation: "ленивый; лениться", example: "他太懒 [tā tài lǎn] — он слишком ленив" },
{ id: 869, char: "浪费", pinyin: "làngfèi", translation: "транжирить; растрачивать; напрасно тратить; расточительство", example: "" },
{ id: 870, char: "浪漫", pinyin: "lànmàn", translation: "романтический; романтичный", example: "" },
{ id: 871, char: "老虎", pinyin: "lǎohǔ", translation: "тигр", example: "" },
{ id: 872, char: "冷静", pinyin: "lěngjìng", translation: "хладнокровный, невозмутимый; трезвый; хладнокровие", example: "" },
{ id: 873, char: "离开", pinyin: "líkāi", translation: "оставить, покинуть; уйти (из); расстаться", example: "" },
{ id: 874, char: "理发", pinyin: "lǐfà", translation: "стричься; причёсываться", example: "" },
{ id: 875, char: "理解", pinyin: "lǐjiě", translation: "понимать, осмысливать: уяснять", example: "" },
{ id: 876, char: "理想", pinyin: "lǐxiǎng", translation: "идеал; идеалы; идеальный", example: "" },
{ id: 877, char: "礼貌", pinyin: "lǐmào", translation: "вежливость; приличия; вежливый", example: "有礼貌 [yǒu lǐmào] — быть вежливым; вежливый" },
{ id: 878, char: "礼物", pinyin: "lǐwù", translation: "подарок; подношение", example: "" },
{ id: 879, char: "厉害", pinyin: "lìhai", translation: "вредный, опасный; критический (о болезни); лютый, жестокий, безжалостный, зверский; ярый, лихой; крутой, сильный", example: "" },
{ id: 880, char: "力气", pinyin: "lìqi", translation: "физическая сила", example: "" },
{ id: 881, char: "例如", pinyin: "lìrú", translation: "например", example: "" },
{ id: 882, char: "历史", pinyin: "lìshǐ", translation: "история; исторический", example: "" },
{ id: 883, char: "俩", pinyin: "liǎ", translation: "два, оба; вдвоём", example: "咱俩 [zánliǎ] — мы (вдвоём)" },
{ id: 884, char: "连", pinyin: "lián", translation: "вместе (с); даже", example: "连你一共五个人 [lián nǐ yīgòng wǔge rén] — вместе с тобой пять человек 连他也来了 [lián tā yě láile] — пришёл даже он" },
{ id: 885, char: "联系", pinyin: "liánxì", translation: "связывать(ся); вступать в контакт; связь", example: "" },
{ id: 886, char: "凉快", pinyin: "liángkuai", translation: "прохладный; прохладно", example: "" },
{ id: 887, char: "亮", pinyin: "liàng", translation: "светлый; яркий", example: "电灯很亮 [diàndēng hěn liàng] — лампочка горит очень ярко" },
{ id: 888, char: "聊天", pinyin: "liáotiān", translation: "болтать, трепаться, судачить", example: "" },
{ id: 889, char: "另外", pinyin: "lìngwài", translation: "кроме того, сверх того", example: "" },
{ id: 890, char: "留", pinyin: "liú", translation: "остаться; задержаться", example: "他留在家里了 [tā liú zài jiāli le] — он остался дома" },
{ id: 891, char: "留学", pinyin: "liúxué", translation: "учиться за границей", example: "" },
{ id: 892, char: "流泪", pinyin: "liúlèi", translation: "проливать (ронять) слёзы", example: "" },
{ id: 893, char: "流利", pinyin: "liúlì", translation: "бегло, свободно", example: "" },
{ id: 894, char: "流行", pinyin: "liúxíng", translation: "быть в моде; иметь хождение [распространение]; модный", example: "流行色 [liúxíngsè] — модный цвет" },
{ id: 895, char: "乱", pinyin: "luàn", translation: "беспорядочный, хаотичный; хаотично, беспорядочно; как попало", example: "乱说 [luànshuō] — говорить что попало" },
{ id: 896, char: "律师", pinyin: "lǜshī", translation: "адвокат", example: "" },
{ id: 897, char: "麻烦", pinyin: "máfan", translation: "хлопотливый; беспокойный; хлопоты; беспокойство", example: "对不起 , 麻烦你了 [duìbuqǐ, máfan nǐ le] — извините, что побеспокоил вас; извините за беспокойство" },
{ id: 898, char: "马虎", pinyin: "mǎhu", translation: "небрежно; спустя рукава, как попало", example: "" },
{ id: 899, char: "满", pinyin: "mǎn", translation: "полный; доверху; наполнять", example: "满满的一桶水 [mǎnmǎnde yī tǒng shuǐ] — полное ведро воды 满上一杯 [mǎnshàng yī bēi] — наполнить бокал" },
{ id: 900, char: "毛巾", pinyin: "máojīn", translation: "шерстяной шарф; мохнатое (махровое) полотенце", example: "" },
{ id: 901, char: "梦", pinyin: "mèng", translation: "сон; сновидение; грёзы", example: "作梦 [zuòmèng] — видеть сон; сниться" },
{ id: 902, char: "密码", pinyin: "mìmǎ", translation: "шифр; код", example: "" },
{ id: 903, char: "免费", pinyin: "miǎnfèi", translation: "бесплатный", example: "" },
{ id: 904, char: "民族", pinyin: "mínzú", translation: "нация; национальность; национальный", example: "少数民族 [shǎoshù mínzú] — национальные меньшинства" },
{ id: 905, char: "母亲", pinyin: "mǔqīn", translation: "мать", example: "" },
{ id: 906, char: "目的", pinyin: "mùdì", translation: "цель", example: "" },
{ id: 907, char: "耐心", pinyin: "nàixīn", translation: "терпеливый; терпеливо; терпение", example: "" },
{ id: 908, char: "难道", pinyin: "nándào", translation: "неужели, разве", example: "" },
{ id: 909, char: "难受", pinyin: "nánshòu", translation: "трудно вынести; невозможно вытерпеть", example: "热得难受 [rède nánshòu] — нестерпимо жарко" },
{ id: 910, char: "内", pinyin: "nèi", translation: "внутренний", example: "内乱 [nèiluàn] — внутренние беспорядки" },
{ id: 911, char: "内容", pinyin: "nèiróng", translation: "содержание; содержимое", example: "" },
{ id: 912, char: "能力", pinyin: "nénglì", translation: "способность; сила", example: "工作能力 [gōngzuò nénglì] — работоспособность" },
{ id: 913, char: "年级", pinyin: "niánjí", translation: "класс, курс", example: "" },
{ id: 914, char: "年龄", pinyin: "niánlíng", translation: "возраст", example: "" },
{ id: 915, char: "年轻", pinyin: "niánqīng", translation: "молодой; молодость", example: "年轻化 [niánqīnghuà] — молодеть; омолаживание" },
{ id: 916, char: "鸟", pinyin: "niǎo", translation: "птица; птицы", example: "" },
{ id: 917, char: "农村", pinyin: "nóngcūn", translation: "деревня; село; деревенский", example: "" },
{ id: 918, char: "弄", pinyin: "nòng", translation: "играть; забавляться; делать, сделать", example: "弄小猫 [nòng xiǎomāo] — играть с котёнком 弄饭 [nòngfàn] — готовить обед" },
{ id: 919, char: "暖和", pinyin: "nuǎnhuo", translation: "тёплый; тепло; теплеть", example: "" },
{ id: 920, char: "偶尔", pinyin: "ǒu'ěr", translation: "иногда; время от времени, по временам", example: "" },
{ id: 921, char: "排列", pinyin: "páiliè", translation: "расставлять [ставить] по порядку", example: "" },
{ id: 922, char: "判断", pinyin: "pànduàn", translation: "определять, решать; определение, решение; судить, оценивать; полагать, считать", example: "" },
{ id: 923, char: "陪", pinyin: "péi", translation: "составить компанию; занимать (гостей); сопровождать", example: "陪客人 [péi kèrén] — занимать гостей 陪餐 [péicān] — составить компанию за столом [за обедом]" },
{ id: 924, char: "批评", pinyin: "pīpíng", translation: "критиковать; критика", example: "批评家 [pīpíngjiā] — критик" },
{ id: 925, char: "皮肤", pinyin: "pífū", translation: "кожа, кожный покров", example: "皮肤病 [pífūbìng] — кожные болезни" },
{ id: 926, char: "脾气", pinyin: "píqi", translation: "характер; нрав; норов", example: "坏脾气 [huài píqi] — плохой характер 有脾气的人 [yǒupíqide rén] — вспыльчивый [раздражительный] человек" },
{ id: 927, char: "篇", pinyin: "piān", translation: "глава; раздел; часть", example: "上篇 [shàngpiān] — первая часть [глава]" },
{ id: 928, char: "骗", pinyin: "piàn", translation: "обманывать; выманивать", example: "骗人 [piànrén] — обманывать людей; мошенничать; мошеннический" },
{ id: 929, char: "乒乓球", pinyin: "pīngpāngqiú", translation: "настольный теннис, пинг-понг", example: "乒乓球拍 [pīngpāngqiúpāi] — ракетка для игры в настольный теннис" },
{ id: 930, char: "平时", pinyin: "píngshí", translation: "обычно; в обычное время; обычный; будничный", example: "" },
{ id: 931, char: "瓶子", pinyin: "píngzi", translation: "бутылка; флакон", example: "" },
{ id: 932, char: "破", pinyin: "pò", translation: "сломать; разрушить; порвать; поранить", example: "他手破了 [tā shǒu pòle] — он поранил руку 破常规 [pò chángguī] — поломать старые порядки 破记录 [pò jìlù] — побить рекорд" },
{ id: 933, char: "普遍", pinyin: "pǔbiàn", translation: "всеобщий; универсальный; распространённый", example: "普遍裁军 [pǔbiàn cáijūn] — всеобщее разоружение" },
{ id: 934, char: "其次", pinyin: "qícì", translation: "затем; потом; далее; следующий; во-вторых", example: "" },
{ id: 935, char: "其中", pinyin: "qízhōng", translation: "среди них; в том числе", example: "" },
{ id: 936, char: "起飞", pinyin: "qǐfēi", translation: "подняться в воздух, взлететь", example: "" },
{ id: 937, char: "起来", pinyin: "qǐlái", translation: "глагольный суффикс, указывающий на а) движение снизу вверх б) на начало действия в) завершённость действия", example: "飞起来 [fēiqǐlái] — взлететь 说起来 [shuōqǐlái] — заговорить 把东西收拾起来 [bǎ dōngxi shōushiqǐlái] — собрать [убрать] вещи" },
{ id: 938, char: "气候", pinyin: "qìhòu", translation: "погода; климат", example: "" },
{ id: 939, char: "千万", pinyin: "qiānwàn", translation: "во что бы то ни стало; ни в коем случае (перед отрицанием)", example: "" },
{ id: 940, char: "签证", pinyin: "qiānzhèng", translation: "виза", example: "入境签证 [rùjìng qiānzhèng] — въездная виза" },
{ id: 941, char: "墙", pinyin: "qiáng", translation: "стена; ограда; забор", example: "城墙 [chéngqiáng] — городская стена 墙报 [qiángbào] — стенная газета" },
{ id: 942, char: "敲", pinyin: "qiāo", translation: "стучать; колотить; бить", example: "敲门 [qiāo mén] — стучать в дверь 钟敲了两下儿 [zhōng qiāole liǎng xiàr] — часы пробили два" },
{ id: 943, char: "桥", pinyin: "qiáo", translation: "мост", example: "石桥 [shíqiáo] — каменный мост 过桥 [guò qiáo] — пройти [проехать] через мост" },
{ id: 944, char: "巧克力", pinyin: "qiǎokèlì", translation: "шоколад", example: "" },
{ id: 945, char: "亲戚", pinyin: "qīnqi", translation: "родные; родственники; родня", example: "" },
{ id: 946, char: "轻", pinyin: "qīng", translation: "лёгкий; легко", example: "油比水轻 [yóu bǐ shuǐ qīng] — масло легче воды 轻武器 [qīng wǔqì] — лёгкое оружие" },
{ id: 947, char: "轻松", pinyin: "qīngsōng", translation: "расслабиться", example: "" },
{ id: 948, char: "情况", pinyin: "qíngkuàng", translation: "обстановка; обстоятельства; положение", example: "" },
{ id: 949, char: "请假", pinyin: "qǐngjià", translation: "просить [брать] отпуск; отпрашиваться с работы", example: "" },
{ id: 950, char: "请客", pinyin: "qǐngkè", translation: "приглашать гостей; угощать", example: "今天是我请客 [jīntiān shì wǒ qǐngkè] — сегодня угощаю я" },
{ id: 951, char: "穷", pinyin: "qióng", translation: "бедный; нищий", example: "穷国 [qióngguó] — бедная страна" },
{ id: 952, char: "区别", pinyin: "qūbié", translation: "различать; отличать; различие, отличие", example: "" },
{ id: 953, char: "取", pinyin: "qǔ", translation: "брать; взять; получить", example: "取行李 [qǔ xíngli] — получить багаж" },
{ id: 954, char: "全部", pinyin: "quánbù", translation: "целиком; полностью; сполна; весь; полный, целый", example: "" },
{ id: 955, char: "缺点", pinyin: "quēdiǎn", translation: "недостаток; изъян; дефект", example: "" },
{ id: 956, char: "缺少", pinyin: "quēshǎo", translation: "недоставать, не хватать", example: "" },
{ id: 957, char: "却", pinyin: "què", translation: "однако; но; тем не менее", example: "" },
{ id: 958, char: "确实", pinyin: "quèshí", translation: "достоверный; подлинный; действительный", example: "" },
{ id: 959, char: "群", pinyin: "qún", translation: "толпа; скопление; стадо; табун", example: "人群 [rénqún] — толпа людей 群马 [yī qún mǎ] — табун лошадей" },
{ id: 960, char: "然而", pinyin: "rán'ér", translation: "но, однако", example: "" },
{ id: 961, char: "热闹", pinyin: "rènao", translation: "оживлённый; людный; шумный", example: "" },
{ id: 962, char: "人民币", pinyin: "rénmínbì", translation: "народная валюта (в юанях, деньги КНР)", example: "" },
{ id: 963, char: "任何", pinyin: "rènhé", translation: "любой; какой бы то ни было; всякий", example: "" },
{ id: 964, char: "任务", pinyin: "rènwu", translation: "задача; задание", example: "" },
{ id: 965, char: "扔", pinyin: "rēng", translation: "бросать; кидать", example: "他把没有用的东西扔了 [tā bǎ méiyǒuyòngde dōngxi rēngle] — он выбросил ненужные вещи" },
{ id: 966, char: "仍然", pinyin: "réngrán", translation: "по-прежнему", example: "" },
{ id: 967, char: "日记", pinyin: "rìjì", translation: "дневник", example: "记日记 [jì rìjì] — вести дневник" },
{ id: 968, char: "入口", pinyin: "rùkǒu", translation: "ввозить; импортировать; ввоз; импорт; вход; подъезд (дома); въезд", example: "" },
{ id: 969, char: "软", pinyin: "ruǎn", translation: "мягкий; гибкий", example: "软面包 [ruǎn miànbāo] — мягкий хлеб 软风 [ruǎnfēng] — ласковый ветерок" },
{ id: 970, char: "散步", pinyin: "sànbù", translation: "прогуливаться, совершать прогулку", example: "" },
{ id: 971, char: "森林", pinyin: "sēnlín", translation: "лес; лесной", example: "" },
{ id: 972, char: "沙发", pinyin: "shāfā", translation: "диван, софа", example: "" },
{ id: 973, char: "商量", pinyin: "shāngliáng", translation: "обсуждать; советоваться", example: "" },
{ id: 974, char: "伤心", pinyin: "shāngxīn", translation: "огорчаться; сокрушаться; убиваться", example: "" },
{ id: 975, char: "稍微", pinyin: "shāowēi", translation: "немного; немножко; чуть", example: "" },
{ id: 976, char: "社会", pinyin: "shèhuì", translation: "общество; общественный; социальный", example: "国际社会 [guójì shèhuì] — мировое сообщество" },
{ id: 977, char: "深", pinyin: "shēn", translation: "глубокий; глубина", example: "一口深井 [yī kǒu shēnjǐng] — глубокий колодец 深夜 [shēnyè] — глубокая ночь" },
{ id: 978, char: "申请", pinyin: "shēnqǐng", translation: "подавать заявление; ходатайствовать; просить; ходатайство; просьба", example: "申请书 [shēnqǐngshū] — заявление; прошение; ходатайство" },
{ id: 979, char: "甚至", pinyin: "shènzhì", translation: "вплоть до того; что; даже; а то и (даже)", example: "" },
{ id: 980, char: "生活", pinyin: "shēnghuó", translation: "жизнь; бытие; сущестовование", example: "生活方式 [shēnghuó fāngshì] — образ жизни" },
{ id: 981, char: "生命", pinyin: "shēngmìng", translation: "жизнь", example: "牺牲生命 [xīshēng shēngmìng] — пожертвовать жизнью" },
{ id: 982, char: "省", pinyin: "shěng", translation: "экономить; беречь", example: "省钱 [shěngqián] — экономить деньги 省力 [shěnglì] — беречь силы" },
{ id: 983, char: "剩", pinyin: "shèng", translation: "оставаться; быть в остатке; оставшийся", example: "只剩了一个人 [zhǐ shèngle yīge rén] — остался только один человек 剩货 [shènghuò] — оставшийся товар; остатки (товара)" },
{ id: 984, char: "失败", pinyin: "shībài", translation: "поражение; неудача; потерпеть поражение [неудачу]", example: "" },
{ id: 985, char: "失望", pinyin: "shīwàng", translation: "разочароваться; разочарование", example: "" },
{ id: 986, char: "师傅", pinyin: "shīfu", translation: "мастер; наставник", example: "" },
{ id: 987, char: "湿润", pinyin: "shīrùn", translation: "влажный; сырой", example: "" },
{ id: 988, char: "狮子", pinyin: "shīzi", translation: "лев", example: "" },
{ id: 989, char: "十分", pinyin: "shífēn", translation: "в полной мере; чрезвычайно, весьма, очень", example: "" },
{ id: 990, char: "实际", pinyin: "shíjì", translation: "реальный; фактический; реальность; действительность", example: "实际行动 [shíjì xíngdòng] — реальные действия 实际工资 [shíjì gōngzī] — реальная заработная плата" },
{ id: 991, char: "实在", pinyin: "shízài", translation: "правдивый; настоящий; действительный", example: "" },
{ id: 992, char: "食品", pinyin: "shípǐn", translation: "продукты (питания); пищевые продукты", example: "食品店 [shípǐndiàn] — продовольственный магазин" },
{ id: 993, char: "使用", pinyin: "shǐyòng", translation: "использовать(ся); применять; употреблять; применение", example: "使用武力 [shǐyòng wǔlì] — применять силу" },
{ id: 994, char: "试", pinyin: "shì", translation: "пробовать; примерять; испытывать; экзамен", example: "试衣服 [shì yīfu] — примерять одежду 笔试 [bǐshì] — письменный экзамен" },
{ id: 995, char: "市场", pinyin: "shìchǎng", translation: "рынок; базар", example: "市场经济 [shìchǎng jīngjì] — рыночная экономика" },
{ id: 996, char: "适合", pinyin: "shìhé", translation: "соответствовать, подходить", example: "" },
{ id: 997, char: "适应", pinyin: "shìyìng", translation: "соответствовать; отвечать чему-либо; применяться; приспосабливаться", example: "" },
{ id: 998, char: "世纪", pinyin: "shìjì", translation: "век; столетие", example: "" },
{ id: 999, char: "收入", pinyin: "shōurù", translation: "доход; поступления (денежные)", example: "个人收入 [gèrén shōurù] — личный доход" },
{ id: 1000, char: "收拾", pinyin: "shōushi", translation: "привести в порядок, прибрать(ся)", example: "收拾屋子 [shōushi wūzi] — прибраться в комнате" },
{ id: 1001, char: "首都", pinyin: "shǒudū", translation: "столица", example: "" },
{ id: 1002, char: "首先", pinyin: "shǒuxiān", translation: "сначала, сперва; в первую очередь; во-первых", example: "" },
{ id: 1003, char: "受不了", pinyin: "shòubuliǎo", translation: "не вынести; невыносимый; в высшей степени тяжёлый", example: "" },
{ id: 1004, char: "受到", pinyin: "shòudào", translation: "получить; пользоваться", example: "受到信任 [shòudào xìnrèn] — пользоваться доверием" },
{ id: 1005, char: "售货员", pinyin: "shòuhuòyuán", translation: "продавец", example: "" },
{ id: 1006, char: "输", pinyin: "shū", translation: "проиграть; потерпеть поражение", example: "我队输了两个球 [wǒ duì shūle liǎngge qiú] — наша команда проиграла два мяча" },
{ id: 1007, char: "熟悉", pinyin: "shúxī", translation: "хорошо знать", example: "" },
{ id: 1008, char: "数量", pinyin: "shùliàng", translation: "количество", example: "" },
{ id: 1009, char: "数字", pinyin: "shùzì", translation: "цифра; цифры; цифровой", example: "控制数字 [kòngzhì shùzì] — контрольные цифры" },
{ id: 1010, char: "帅", pinyin: "shuài", translation: "представительный, видный; солидный", example: "" },
{ id: 1011, char: "顺便", pinyin: "shùnbiàn", translation: "попутно; заодно; кстати", example: "" },
{ id: 1012, char: "顺利", pinyin: "shùnlì", translation: "гладко; успешно; благоприятно", example: "" },
{ id: 1013, char: "顺序", pinyin: "shùnxù", translation: "порядок; очередь", example: "" },
{ id: 1014, char: "说明", pinyin: "shuōmíng", translation: "объяснить, разъяснить, пояснить", example: "" },
{ id: 1015, char: "硕士", pinyin: "shuòshì", translation: "магистр", example: "" },
{ id: 1016, char: "死", pinyin: "sǐ", translation: "смерть; умереть; погибнуть; сдохнуть; мёртвый", example: "累死 [lèisǐ] — до смерти устать" },
{ id: 1017, char: "速度", pinyin: "sùdù", translation: "скорость; темпы", example: "" },
{ id: 1018, char: "塑料袋", pinyin: "sùliào dài", translation: "пластиковый пакет", example: "" },
{ id: 1019, char: "酸", pinyin: "suān", translation: "кислый; прокиснуть", example: "酸白菜 [suān báicài] — кислая [квашеная] капуста" },
{ id: 1020, char: "算", pinyin: "suàn", translation: "считать; подсчитывать; предполагать; рассчитывать", example: "他能写会算 [tā néng xiě huì suàn] — он умеет писать и считать 我算他今天来 [wǒ suàn tā jīntiān lái] — я полагаю, что сегодня он придёт" },
{ id: 1021, char: "随便", pinyin: "suíbiàn", translation: "как угодно, как захочется", example: "随便你的便 [suí nǐde biàn] — как вам угодно" },
{ id: 1022, char: "随着", pinyin: "suízhe", translation: "по мере; вслед за", example: "随着形势的发展 [suízhe xíngshìde fāzhǎn] — по мере развития ситуации" },
{ id: 1023, char: "孙子", pinyin: "sūnzi", translation: "внук", example: "" },
{ id: 1024, char: "所有", pinyin: "suǒyǒu", translation: "собственность; имущество", example: "" },
{ id: 1025, char: "台", pinyin: "tái", translation: "башня; вышка; сцена, арена; сч. сл.для машин", example: "了望台 [liàowàngtái] — наблюдательная вышка 台拖拉机 [yī tái tuōlājī] — один трактор" },
{ id: 1026, char: "抬", pinyin: "tái", translation: "поднять; повысить", example: "抬价 [táijià] — поднять [повысить] цену" },
{ id: 1027, char: "态度", pinyin: "tàidu", translation: "позиция; отношение", example: "" },
{ id: 1028, char: "谈", pinyin: "tán", translation: "беседовать, разговаривать; говорить; излагать", example: "我们不谈这个 [wǒmen bùtán zhège] — не будем об этом говорить" },
{ id: 1029, char: "弹钢琴", pinyin: "tán gāngqín", translation: "играть на фортепьяно", example: "" },
{ id: 1030, char: "汤", pinyin: "tāng", translation: "суп", example: "红甜菜汤 [hóngtiáncàitāng] — борщ" },
{ id: 1031, char: "躺", pinyin: "tǎng", translation: "лечь; лежать (о человеке)", example: "躺下睡觉 [tǎngxià shuìjiǎo] — лечь спать" },
{ id: 1032, char: "趟", pinyin: "tàng", translation: "сч. сл. раз; сч. сл. для поездов", example: "你到莫斯科去过几趟 ? [nǐ dào mòsīkē qùguo jǐtàng] — сколько раз вы бывали в Москве?这趟车是去北京的 [zhètàng chē shì qù běijīngde] — этот поезд идёт в Пекин" },
{ id: 1033, char: "讨论", pinyin: "tǎolùn", translation: "обсуждать, дискутировать; обсуждение; прения", example: "讨论会 [tǎolùnhuì] — дискуссия; диспут" },
{ id: 1034, char: "讨厌", pinyin: "tǎoyàn", translation: "надоесть; опротиветь; надоедливый; докучливый", example: "" },
{ id: 1035, char: "特点", pinyin: "tèdiǎn", translation: "особенность; своеобразие; специфика", example: "" },
{ id: 1036, char: "提供", pinyin: "tígōng", translation: "предоставлять; поставлять; снабжать", example: "" },
{ id: 1037, char: "提前", pinyin: "tíqián", translation: "досрочно; раньше установленного срока", example: "" },
{ id: 1038, char: "提醒", pinyin: "tíxǐng", translation: "напоминать; подсказывать", example: "" },
{ id: 1039, char: "填空", pinyin: "tiánkōng", translation: "занять вакансию; заполнять пустые места", example: "" },
{ id: 1040, char: "条件", pinyin: "tiáojiàn", translation: "условие; условный", example: "生活条件 [shēnghuò tiáojiàn] — условия жизни" },
{ id: 1041, char: "停止", pinyin: "tíngzhǐ", translation: "прекратить, остановить, положить конец", example: "" },
{ id: 1042, char: "挺", pinyin: "tǐng", translation: "весьма; чрезвычайно, исключительно", example: "挺好 [tǐng hǎo] — исключительно хорошо" },
{ id: 1043, char: "通过", pinyin: "tōngguò", translation: "проходить через", example: "" },
{ id: 1044, char: "通知", pinyin: "tōngzhī", translation: "сообщать; извещать; уведомлять", example: "" },
{ id: 1045, char: "同情", pinyin: "tóngqíng", translation: "сочувствовать; симпатизировать; сочувствие; симпатия", example: "" },
{ id: 1046, char: "推", pinyin: "tuī", translation: "толкать; подталкивать", example: "推门 [tuī mén] — толкнуть дверь" },
{ id: 1047, char: "推迟", pinyin: "tuīchí", translation: "отсрочить, отложить", example: "" },
{ id: 1048, char: "脱", pinyin: "tuō", translation: "снять (одежду, обувь)", example: "脱衣服 [tuō yīfu] — снять одежду, раздеться" },
{ id: 1049, char: "袜子", pinyin: "wàzi", translation: "носки; чулки", example: "" },
{ id: 1050, char: "完全", pinyin: "wánquán", translation: "полный; целый; совершенный; законченный", example: "" },
{ id: 1051, char: "往", pinyin: "wǎng", translation: "направляться куда-либо", example: "往莫斯科访问 [wǎng mòsīkē fǎngwèn] — направиться в Москву с визитом" },
{ id: 1052, char: "往往", pinyin: "wǎngwǎng", translation: "сплошь и рядом; часто; постоянно", example: "" },
{ id: 1053, char: "网球", pinyin: "wǎngqiú", translation: "теннис", example: "" },
{ id: 1054, char: "网站", pinyin: "wǎngzhàn", translation: "интернет-сайт", example: "" },
{ id: 1055, char: "危险", pinyin: "wēixiǎn", translation: "опасность; опасный; угрожающий", example: "" },
{ id: 1056, char: "位", pinyin: "wèi", translation: "место; позиция", example: "占第一位 [zhàn dì yī wèi] — занять первое место" },
{ id: 1057, char: "为", pinyin: "wéi", translation: "делать; действовать; поступать; быть, являться", example: "所作所为 [suǒzuò suǒwéi] — всё, что сделано; всё сделанное 他为人很好 [tā wéi rén hěn hǎo] — как человек, он очень хороший" },
{ id: 1058, char: "为了", pinyin: "wèile", translation: "для; ради; в целях; для того, чтобы", example: "" },
{ id: 1059, char: "味道", pinyin: "wèidao", translation: "вкус", example: "" },
{ id: 1060, char: "温度", pinyin: "wēndù", translation: "температура", example: "" },
{ id: 1061, char: "文章", pinyin: "wénzhāng", translation: "статья; сочинение", example: "" },
{ id: 1062, char: "握手", pinyin: "wòshǒu", translation: "пожимать руку, подавать руку", example: "" },
{ id: 1063, char: "污染", pinyin: "wūrǎn", translation: "загрязнять; загрязнение", example: "环境污染 [huánjìng wūrǎn] — загрязнение окружающей среды" },
{ id: 1064, char: "无", pinyin: "wú", translation: "не; не иметь; без-", example: "无酒精性饮料 [wújiǔjīngxìng yǐnliào] — безалкогольные напитки" },
{ id: 1065, char: "无聊", pinyin: "wúliáo", translation: "скука; скучный", example: "" },
{ id: 1066, char: "无论", pinyin: "wúlùn", translation: "независимо от чего-либо", example: "无论如何 [wúlùn rúhé] — как бы то ни было; в любом случае" },
{ id: 1067, char: "误会", pinyin: "wùhuì", translation: "неправильно понять; недоразумение", example: "" },
{ id: 1068, char: "西", pinyin: "xī", translation: "запад; западный", example: "从西往东 [cóng xī wǎng dōng] — с запада на восток" },
{ id: 1069, char: "西红柿", pinyin: "xīhóngshì", translation: "помидор; томат", example: "" },
{ id: 1070, char: "吸引", pinyin: "xīyǐn", translation: "вовлекать; привлекать", example: "" },
{ id: 1071, char: "洗手间", pinyin: "xǐshǒujiān", translation: "туалет", example: "" },
{ id: 1072, char: "洗衣机", pinyin: "xǐyījī", translation: "стиральная машина", example: "" },
{ id: 1073, char: "洗澡", pinyin: "xǐzǎo", translation: "мыться; принимать ванну; купаться", example: "" },
{ id: 1074, char: "咸", pinyin: "xián", translation: "солёный", example: "咸鱼 [xiányú] — солёная рыба" },
{ id: 1075, char: "现代", pinyin: "xiàndài", translation: "современный", example: "" },
{ id: 1076, char: "羡慕", pinyin: "xiànmù", translation: "завидовать; зависть", example: "" },
{ id: 1077, char: "限制", pinyin: "xiànzhì", translation: "ограничить; ограничение", example: "无限制地 [wúxiànzhìde] — без всяких ограничений; неограниченно" },
{ id: 1078, char: "香", pinyin: "xiāng", translation: "ароматный; душистый; вкусный; аппетитный", example: "香花 [xiānghuā] — душистые цветы 饭很香 [fàn hěn xiāng] — еда очень вкусная" },
{ id: 1079, char: "相反", pinyin: "xiāngfǎn", translation: "напроротив; наоборот", example: "" },
{ id: 1080, char: "详细", pinyin: "xiángxì", translation: "подробный; детальный", example: "" },
{ id: 1081, char: "响", pinyin: "xiǎng", translation: "звучный; звонкий", example: "这个铃真响 [zhège líng zhēn xiǎng] — этот колокольчик очень звонкий" },
{ id: 1082, char: "消息", pinyin: "xiāoxi", translation: "известия; новости; сообщения; сведения", example: "" },
{ id: 1083, char: "小说", pinyin: "xiǎoshuō", translation: "беллетристика; повесть; рассказ; роман", example: "" },
{ id: 1084, char: "笑话", pinyin: "xiàohuà", translation: "шутка; анекдот", example: "" },
{ id: 1085, char: "效果", pinyin: "xiàoguǒ", translation: "эффект; результат", example: "" },
{ id: 1086, char: "辛苦", pinyin: "xīnkǔ", translation: "упорно трудиться; в поте лица; не щадя сил", example: "" },
{ id: 1087, char: "心情", pinyin: "xīnqíng", translation: "настроение; расположение духа", example: "" },
{ id: 1088, char: "信任", pinyin: "xìnrèn", translation: "доверие; доверять", example: "" },
{ id: 1089, char: "信心", pinyin: "xìnxīn", translation: "уверенность; чувство уверенности; вера", example: "" },
{ id: 1090, char: "信用卡", pinyin: "xìnyòngkǎ", translation: "Кредитная карта", example: "" },
{ id: 1091, char: "兴奋", pinyin: "xīngfèn", translation: "возбуждение; возбуждённый; приподнятый", example: "" },
{ id: 1092, char: "行", pinyin: "xíng", translation: "можно; разрешается; ладно", example: "不行 — нельзя; не полагается" },
{ id: 1093, char: "醒", pinyin: "xǐng", translation: "проснуться; пробудиться; очнуться; бодрствовать", example: "他醒来了 [tā xǐngláile] — он проснулся [очнулся]" },
{ id: 1094, char: "性别", pinyin: "xìngbié", translation: "пол; половые различия", example: "" },
{ id: 1095, char: "性格", pinyin: "xìnggé", translation: "характер; натура", example: "" },
{ id: 1096, char: "幸福", pinyin: "xìngfú", translation: "счастье; счастливый", example: "" },
{ id: 1097, char: "修", pinyin: "xiū", translation: "ремонтировать; исправлять; чинить", example: "修表 [xiūbiǎo] — чинить часы" },
{ id: 1098, char: "许多", pinyin: "xǔduō", translation: "много; множество", example: "" },
{ id: 1099, char: "血", pinyin: "xuè", translation: "кровь", example: "血压 [xuèyā] — кровяное давление 血战 [xuèzhàn] — кровопролитное сражение" },
{ id: 1100, char: "压力", pinyin: "yālì", translation: "давление; нажим", example: "" },
{ id: 1101, char: "牙膏", pinyin: "yágāo", translation: "зубная паста", example: "" },
{ id: 1102, char: "呀", pinyin: "ya", translation: "фразовая частица", example: "" },
{ id: 1103, char: "盐", pinyin: "yán", translation: "соль", example: "" },
{ id: 1104, char: "严格", pinyin: "yángé", translation: "строгий; строго", example: "严格说来 [yángé shuōlái] — строго говоря 严格要求 [yángé yāoqiú] — строго требовать" },
{ id: 1105, char: "严重", pinyin: "yánzhòng", translation: "серьёзный; тяжёлый", example: "" },
{ id: 1106, char: "研究生", pinyin: "yánjiūshēng", translation: "аспирант", example: "" },
{ id: 1107, char: "演出", pinyin: "yǎnchū", translation: "представлять; исполнять; представление; выступление", example: "" },
{ id: 1108, char: "演员", pinyin: "yǎnyuán", translation: "артист; актёр", example: "" },
{ id: 1109, char: "亚洲", pinyin: "yàzhōu", translation: "Азия; азиатский", example: "" },
{ id: 1110, char: "阳光", pinyin: "yángguāng", translation: "солнечный свет; солнечные лучи", example: "" },
{ id: 1111, char: "养成", pinyin: "yǎngchéng", translation: "выработать; привить (напр., привычку)", example: "" },
{ id: 1112, char: "样子", pinyin: "yàngzi", translation: "вид; модель; фасон; вид; выражение лица", example: "" },
{ id: 1113, char: "邀请", pinyin: "yāoqǐng", translation: "приглашать; приглашение", example: "邀请费 [yāoqǐngfèi] — представительские расходы" },
{ id: 1114, char: "钥匙", pinyin: "yàoshi", translation: "ключ", example: "" },
{ id: 1115, char: "也许", pinyin: "yěxǔ", translation: "возможно, может быть", example: "" },
{ id: 1116, char: "页", pinyin: "yè", translation: "страница; лист", example: "两页 [liǎng yè] — две страницы" },
{ id: 1117, char: "叶子", pinyin: "yèzi", translation: "лист; листва", example: "" },
{ id: 1118, char: "一切", pinyin: "yīqiè", translation: "все; весь", example: "" },
{ id: 1119, char: "以", pinyin: "yǐ", translation: "с помощью; посредством", example: "以新成绩迎接国庆 [yǐ xīn chéngjī yíngjiē guóqìng] — встретить национальный праздник новыми успехами" },
{ id: 1120, char: "亿", pinyin: "yì", translation: "сто миллионов", example: "" },
{ id: 1121, char: "意见", pinyin: "yìjian", translation: "мнение, взгляд; точка зрения", example: "意见簿 [yìjianbù] — книга предложений [жалоб]" },
{ id: 1122, char: "艺术", pinyin: "yìshù", translation: "искусство; художество; художественный", example: "" },
{ id: 1123, char: "因此", pinyin: "yīncǐ", translation: "в связи с этим, поэтому", example: "" },
{ id: 1124, char: "饮料", pinyin: "yǐnliào", translation: "напитки; питьё", example: "" },
{ id: 1125, char: "引起", pinyin: "yǐnqǐ", translation: "возбуждать; вызывать", example: "" },
{ id: 1126, char: "印象", pinyin: "yìnxiàng", translation: "впечатление", example: "" },
{ id: 1127, char: "赢", pinyin: "yíng", translation: "выиграть; одержать победу; победить", example: "他赢了 [tā yíngle] — он выиграл" },
{ id: 1128, char: "硬", pinyin: "yìng", translation: "твёрдый; жёсткий; крепкий", example: "比钢还硬 [bǐ gāng hái yìng] — твёрже стали" },
{ id: 1129, char: "勇敢", pinyin: "yǒnggǎn", translation: "смелый, храбрый, отважный", example: "" },
{ id: 1130, char: "永远", pinyin: "yǒngyuǎn", translation: "навечно; навсегда; вечно", example: "" },
{ id: 1131, char: "优点", pinyin: "yōudiǎn", translation: "достоинство, преимущество; плюс", example: "" },
{ id: 1132, char: "优秀", pinyin: "yōuxiù", translation: "превосходный; замечательный; прекрасный", example: "" },
{ id: 1133, char: "幽默", pinyin: "yōumò", translation: "юмор; юмористический", example: "" },
{ id: 1134, char: "由", pinyin: "yóu", translation: "из; от; с; через", example: "由边门出去 [yóu biānmén chūqu] — выходить через боковую дверь 由东往西 [yóu dōng wǎng xī] — с востока на запад" },
{ id: 1135, char: "由于", pinyin: "yóuyú", translation: "из-за того, что; вследствие того, что; благодаря тому, что", example: "" },
{ id: 1136, char: "尤其", pinyin: "yóuqí", translation: "в особенности; особенно; тем более", example: "" },
{ id: 1137, char: "有趣", pinyin: "yǒuqù", translation: "интересный; интересно; забавно", example: "" },
{ id: 1138, char: "友好", pinyin: "yǒuhǎo", translation: "дружба; дружественный", example: "" },
{ id: 1139, char: "友谊", pinyin: "yǒuyì", translation: "дружба; дружеский", example: "友谊赛 [yǒuyìsài] — дружеская встреча" },
{ id: 1140, char: "又", pinyin: "yòu", translation: "опять, снова", example: "今天又下雨了 [jīntiān yòu xiàyǔle] — сегодня опять идёт дождь" },
{ id: 1141, char: "愉快", pinyin: "yúkuài", translation: "радостный; радость", example: "" },
{ id: 1142, char: "于是", pinyin: "yúshì", translation: "таким образом; и тогда", example: "" },
{ id: 1143, char: "与", pinyin: "yǔ", translation: "и; с; к", example: "这件事与他没有关系 [zhè jiàn shì yǔ tā méiyǒu guānxi] — это дело не имеет к нему отношения" },
{ id: 1144, char: "语法", pinyin: "yǔfǎ", translation: "грамматика; грамматический", example: "" },
{ id: 1145, char: "语言", pinyin: "yǔyán", translation: "язык; речь; языковый", example: "" },
{ id: 1146, char: "羽毛球", pinyin: "yǔmáoqiú", translation: "бадминтон", example: "" },
{ id: 1147, char: "预习", pinyin: "yùxí", translation: "предварительное ознакомление с материалом", example: "" },
{ id: 1148, char: "圆", pinyin: "yuán", translation: "круглый", example: "圆桌子 [yuán zhuōzi] — круглый стол" },
{ id: 1149, char: "原来", pinyin: "yuánlái", translation: "с самого начала; первоначально; первоначальный", example: "" },
{ id: 1150, char: "原谅", pinyin: "yuánliàng", translation: "извинять; прощать", example: "" },
{ id: 1151, char: "原因", pinyin: "yuányīn", translation: "причина", example: "" },
{ id: 1152, char: "愿意", pinyin: "yuànyì", translation: "желать; хотеть; желание; готовность", example: "" },
{ id: 1153, char: "约会", pinyin: "yuēhuì", translation: "свидание, встреча", example: "" },
{ id: 1154, char: "越", pinyin: "yuè", translation: "перейти через; ещё более", example: "越多越好 [yuè duō yuè hǎo] — чем больше, тем лучше" },
{ id: 1155, char: "阅读", pinyin: "yuèdú", translation: "читать; чтение", example: "" },
{ id: 1156, char: "云", pinyin: "yún", translation: "облако; туча", example: "乌云 [wūyún] — чёрные тучи" },
{ id: 1157, char: "允许", pinyin: "yǔnxǔ", translation: "разрешать; позволять", example: "" },
{ id: 1158, char: "杂志", pinyin: "zázhì", translation: "журнал", example: "" },
{ id: 1159, char: "咱们", pinyin: "zánmen", translation: "мы (включая собеседника)", example: "" },
{ id: 1160, char: "暂时", pinyin: "zànshí", translation: "временный; временно; пока", example: "" },
{ id: 1161, char: "脏", pinyin: "zāng", translation: "грязный; испачкать(ся)", example: "把书弄脏 [bǎ shū nòngzāng] — испачкать книгу" },
{ id: 1162, char: "责任", pinyin: "zérèn", translation: "ответственность; обязанность; долг", example: "不负责任的 [bù fù zérèn de] — безответственный" },
{ id: 1163, char: "增加", pinyin: "zēngjiā", translation: "увеличить(ся); повысить(ся); возрасти", example: "" },
{ id: 1164, char: "增长", pinyin: "zēngzhǎng", translation: "возрастать; расти; увеличиваться; увеличение; рост", example: "" },
{ id: 1165, char: "窄", pinyin: "zhǎi", translation: "узкий; тесный", example: "路太窄 [lù tài zhǎi] — дорога слишком узкая 眼界窄 [yǎnjiè zhǎi] — узкий [ограниченный] кругозор" },
{ id: 1166, char: "招聘", pinyin: "zhāopìn", translation: "приглашать; нанимать (на работу)", example: "" },
{ id: 1167, char: "照相机", pinyin: "zhàoxiàngjī", translation: "фотоаппарат", example: "" },
{ id: 1168, char: "真正", pinyin: "zhēnzhèng", translation: "подлинный; настоящий; истинный", example: "" },
{ id: 1169, char: "整理", pinyin: "zhěnglǐ", translation: "привести в порядок; навести порядок; упорядочить", example: "" },
{ id: 1170, char: "整齐", pinyin: "zhěngqí", translation: "ровный; стройный", example: "" },
{ id: 1171, char: "正常", pinyin: "zhèngcháng", translation: "нормальный; обычный", example: "" },
{ id: 1172, char: "正好", pinyin: "zhènghǎo", translation: "как раз; кстати", example: "" },
{ id: 1173, char: "正确", pinyin: "zhèngquè", translation: "правильный; верный; достоверный", example: "" },
{ id: 1174, char: "正式", pinyin: "zhèngshì", translation: "официальный; официально", example: "正式会谈 [zhèngshì huìtán] — официальные переговоры" },
{ id: 1175, char: "证明", pinyin: "zhèngmíng", translation: "удостоверять; свидетельствовать", example: "" },
{ id: 1176, char: "之", pinyin: "zhī", translation: "показатель определения; употребляется для обозначения дробей и процентов", example: "原因之一 [yuányīn zhī yī] — одна из причин 三分之一 [sānfēn zhī yī] — 1/3" },
{ id: 1177, char: "支持", pinyin: "zhīchí", translation: "поддерживать; поддержка", example: "" },
{ id: 1178, char: "值得", pinyin: "zhíde", translation: "заслуживать; стоить", example: "" },
{ id: 1179, char: "直接", pinyin: "zhíjiē", translation: "прямой; непосредственный", example: "" },
{ id: 1180, char: "植物", pinyin: "zhíwù", translation: "растение; растительный", example: "植物油 [zhíwùyóu] — растительное масло" },
{ id: 1181, char: "职业", pinyin: "zhíyè", translation: "занятие; профессия; профессиональный", example: "职业病 [zhíyèbìng] — профессиональное заболевание" },
{ id: 1182, char: "指", pinyin: "zhǐ", translation: "палец; показывать; указывать", example: "食指 [shízhǐ] — указательный палец" },
{ id: 1183, char: "只好", pinyin: "zhǐhǎo", translation: "быть вынужденным; приходится, остаётся лишь", example: "" },
{ id: 1184, char: "只要", pinyin: "zhǐyào", translation: "если только; стоит лишь", example: "" },
{ id: 1185, char: "质量", pinyin: "zhìliàng", translation: "масса", example: "" },
{ id: 1186, char: "至少", pinyin: "zhìshǎo", translation: "самое малое; минимум", example: "" },
{ id: 1187, char: "制造", pinyin: "zhìzào", translation: "изготавливать; производить", example: "" },
{ id: 1188, char: "中文", pinyin: "zhōngwén", translation: "китайский язык", example: "" },
{ id: 1189, char: "重点", pinyin: "zhòngdiǎn", translation: "ключевой пункт; главное звено", example: "" },
{ id: 1190, char: "重视", pinyin: "zhòngshì", translation: "придавать важное значение; ценить; уделять внимание", example: "" },
{ id: 1191, char: "周围", pinyin: "zhōuwéi", translation: "круг, окружность; периферия", example: "" },
{ id: 1192, char: "猪", pinyin: "zhū", translation: "свинья", example: "养猪 [yǎng zhū] — разводить свиней" },
{ id: 1193, char: "逐渐", pinyin: "zhújiàn", translation: "постепенно", example: "" },
{ id: 1194, char: "主动", pinyin: "zhǔdòng", translation: "активный; инициативный; инициатива", example: "" },
{ id: 1195, char: "主意", pinyin: "zhǔyì", translation: "мнение; идея", example: "" },
{ id: 1196, char: "祝贺", pinyin: "zhùhè", translation: "поздравлять", example: "" },
{ id: 1197, char: "著名", pinyin: "zhùmíng", translation: "знаменитый; известный", example: "" },
{ id: 1198, char: "专门", pinyin: "zhuānmén", translation: "специальный; специально", example: "" },
{ id: 1199, char: "专业", pinyin: "zhuānyè", translation: "специальность; профессия", example: "专业知识 [zhuānyè zhīshi] — профессиональные знания" },
{ id: 1200, char: "赚", pinyin: "zhuàn", translation: "зарабатывать; наживать", example: "他赚了很多钱 [tā zhuànle hěn duō qián] — он нажил [заработал] много денег" },
{ id: 1201, char: "撞", pinyin: "zhuàng", translation: "толкнуть; ударить; наскочить; столкнуться", example: "撞倒 [zhuàngdǎo] — сбить (с ног)" },
{ id: 1202, char: "准确", pinyin: "zhǔnquè", translation: "точный; правильный", example: "准确性 [zhǔnquèxìng] — точность" },
{ id: 1203, char: "准时", pinyin: "zhǔnshí", translation: "вовремя; в установленное время", example: "" },
{ id: 1204, char: "仔细", pinyin: "zǐxì", translation: "тщательный; тщательно; внимательно", example: "" },
{ id: 1205, char: "自然", pinyin: "zìrán", translation: "естественно; конечно; само собой разумеется", example: "" },
{ id: 1206, char: "总结", pinyin: "zǒngjié", translation: "общий итог, резюме, выводы, заключение; отчёт", example: "" },
{ id: 1207, char: "租", pinyin: "zū", translation: "арендовать; снимать (напр., квартиру); брать напрокат", example: "租一所房子 [zū yīsuǒ fángzi] — арендовать дом" },
{ id: 1208, char: "组成", pinyin: "zǔchéng", translation: "образовать; сформировать; составить", example: "组成部分 [zǔchéng bùfen] — составная часть" },
{ id: 1209, char: "组织", pinyin: "zǔzhī", translation: "организовать; образовать; сформировать", example: "" },
{ id: 1210, char: "嘴", pinyin: "zuǐ", translation: "рот; пасть; клюв", example: "张嘴 [zhāng zuǐ] — открыть рот" },
{ id: 1211, char: "最好", pinyin: "zuìhǎo", translation: "самый хороший; лучший; наилучший", example: "" },
{ id: 1212, char: "尊重", pinyin: "zūnzhòng", translation: "уважать; ценить; серьёзный; солидный", example: "" },
{ id: 1213, char: "做生意", pinyin: "zuò shēngyi", translation: "вести торговлю; торговать", example: "" },
];