// Массив всех 150 слов HSK 1 из предоставленного PDF
const hskWords = [
    { id: 1, char: "爱", pinyin: "ài", translation: "любить; любовь; любимый", example: "爱祖国 [ài zǔguó] — любить родину; 母爱 [mǔ'ài] — материнская любовь" },
    { id: 2, char: "八", pinyin: "bā", translation: "восемь; восьмой", example: "" },
    { id: 3, char: "爸爸", pinyin: "bàba", translation: "папа, тятя", example: "" },
    { id: 4, char: "杯子", pinyin: "běizi", translation: "стакан; кружка; бокал; рюмка", example: "" },
    { id: 5, char: "北京", pinyin: "běijīng", translation: "Пекин", example: "" },
    { id: 6, char: "本", pinyin: "běn", translation: "счётное слово для растений, цветов", example: "" },
    { id: 7, char: "不客", pinyin: "bùkēqi", translation: "не церемоньтесь!; не стесняйтесь!", example: "" },
    { id: 8, char: "不", pinyin: "bù", translation: "отрицательная частица не", example: "我不去 [wǒ bùqù] — я не пойду [не поеду]" },
    { id: 9, char: "菜", pinyin: "cài", translation: "овощи; блюдо; пища; стол", example: "种菜 [zhòng cài] — сажать овощи; 中菜 [zhōngcài] — китайская кухня; китайские блюда" },
    { id: 10, char: "茶", pinyin: "chá", translation: "чай", example: "喝茶 [hē chá] — пить чай" },
    { id: 11, char: "吃", pinyin: "chī", translation: "есть, кушать", example: "吃水果 [chī shuǐguǒ] — кушать фрукты; 吃药 [chīyào] — принимать лекарства" },
    { id: 12, char: "出租车", pinyin: "chūzūchē", translation: "такси", example: "" },
    { id: 13, char: "打电话", pinyin: "dǎ diànhuà", translation: "звонить по телефону", example: "" },
    { id: 14, char: "大", pinyin: "dà", translation: "большой; крупный; великий; огромный", example: "大成市 [dà chéngshì] — большой [крупный] город; 大事 [dàshì] — большое [важное] событие" },
    { id: 15, char: "的", pinyin: "de", translation: "суффикс прилагательного; суффикс притяжательности", example: "大的 [dàde] — большой; 父亲的话 [fùqīnde huà] — слова отца" },
    { id: 16, char: "点", pinyin: "diǎn", translation: "капля; немножко, чуточку; точка; запятая", example: "雨点 [yǔdiǎn] — капля дождя; 零点五 [líng diǎn wǔ] — 0,5 [ноль целых пять десятых]" },
    { id: 17, char: "电脑", pinyin: "diànnǎo", translation: "компьютер", example: "电脑软件 [diànnǎo ruǎnjiàn] — программные компоненты компьютера" },
    { id: 18, char: "电视", pinyin: "diànshì", translation: "телевидение; телевизионный", example: "电视连续剧 [diànshì liánxùjù] — телесериал; 电视片 [diànshìpiàn] — телефильм" },
    { id: 19, char: "电影", pinyin: "diànyǐng", translation: "кино", example: "电影片 [diànyǐngpiàn] — кинофильм" },
    { id: 20, char: "东西", pinyin: "dōngxi", translation: "вещь; предмет", example: "" },
    { id: 21, char: "都", pinyin: "dōu", translation: "все; всё", example: "他们都去 [tāmen dōu qù] — они все пойдут" },
    { id: 22, char: "读", pinyin: "dú", translation: "читать; зачитывать", example: "读报 [dúbào] — читать газеты; читка газет (вслух); 读大学 [dú dàxué] — учиться в университете" },
    { id: 23, char: "对不起", pinyin: "duìbuqǐ", translation: "виноват!, простите!, извините!", example: "" },
    { id: 24, char: "多", pinyin: "duō", translation: "много; многочисленный; свыше", example: "事情很多 [shìqíng hěnduō] — дел очень много; 一年多 [yīnián duō] — год с лишним; 多糟! [duō zāo] — до чего скверно!" },
    { id: 25, char: "多少", pinyin: "duōshǎo", translation: "сколько?", example: "" },
    { id: 26, char: "儿子", pinyin: "érzi", translation: "сын", example: "" },
    { id: 27, char: "二", pinyin: "èr", translation: "два; второй", example: "二路公共汽车 [èrlù gōnggòng qìchē] — автобус номер два; 二中全会 [èrzhōngquánhuì] — второй пленум ЦК" },
    { id: 28, char: "饭馆", pinyin: "fànguǎn", translation: "ресторан; столовая", example: "" },
    { id: 29, char: "飞机", pinyin: "fēijī", translation: "самолёт", example: "" },
    { id: 30, char: "分钟", pinyin: "fēnzhōng", translation: "минута", example: "" },
    { id: 31, char: "高兴", pinyin: "gāoxìng", translation: "радоваться; радостный", example: "" },
    { id: 32, char: "个", pinyin: "gè", translation: "универсальное сч. сл.; отдельный; индивидуальный", example: "洗个澡 [xǐgè zǎo] — помыться" },
    { id: 33, char: "工作", pinyin: "gōngzuò", translation: "работать; работа", example: "" },
    { id: 34, char: "狗", pinyin: "gǒu", translation: "собака; собачий", example: "猎狗 [liègǒu] — охотничья собака; 狗吠 [gǒufèi] — собачий лай" },
    { id: 35, char: "汉语", pinyin: "hànyǔ", translation: "китайский язык", example: "" },
    { id: 36, char: "好", pinyin: "hǎo", translation: "хороший; хорошо; приятный; удобный", example: "一切都好 [yīqiè dōu hǎo] — всё хорошо; всё в порядке; 好听 [hǎotīng] — приятный для слуха" },
    { id: 37, char: "喝", pinyin: "hē", translation: "пить", example: "喝茶 [hē chá] — пить чай; 爱喝 [ài hē] — любить выпить" },
    { id: 38, char: "和", pinyin: "hé", translation: "мирный; союз и; предлог с", example: "和谈 [hétán] — мирные переговоры; 和大家一起 [hé dàjiā yīqǐ] — вместе со всеми" },
    { id: 39, char: "很", pinyin: "hěn", translation: "очень; весьма", example: "很好 [hěnhǎo] — очень хорошо" },
    { id: 40, char: "后面", pinyin: "hòumiàn", translation: "задняя сторона; зад; позади, сзади; задний", example: "" },
    { id: 41, char: "回", pinyin: "huí", translation: "возвращаться", example: "回国 [huíguó] — вернуться на родину; 回过头来 [huíguòtóulái] — повернуть голову назад; обернуться" },
    { id: 42, char: "会", pinyin: "huì", translation: "уметь; мочь; владеть; собрание; заседание", example: "今天我们有个会 [jīntiān wǒmen yǒuge huì] — сегодня у нас собрание [заседание]; 我不会游泳 [wǒ bùhuì yóuyǒng] — я не умею плавать" },
    { id: 43, char: "火车站", pinyin: "huǒchēzhàn", translation: "вокзал; железнодорожная станция", example: "" },
    { id: 44, char: "几", pinyin: "jǐ", translation: "сколько?; несколько; немного", example: "几个人？[jǐge rén] — сколько человек?" },
    { id: 45, char: "家", pinyin: "jiā", translation: "семья; семейство; дом; домашний", example: "我的家 [wǒdejiā] — моя семья; 家事 [jiāshì] — домашние дела" },
    { id: 46, char: "叫", pinyin: "jiào", translation: "кричать; крик; звать; подзывать; вызывать", example: "鸡叫 [jījiào] — крик петуха; 他叫什么名字？ [tā jiào shénme míngzi] — как его зовут?, как его имя?" },
    { id: 47, char: "今天", pinyin: "jīntiān", translation: "сегодня; нынешний день", example: "" },
    { id: 48, char: "九", pinyin: "jiǔ", translation: "девять; девятый", example: "" },
    { id: 49, char: "开", pinyin: "kāi", translation: "открывать; управлять; вести; включать", example: "开门 [kāimén] — открыть дверь [ворота]; 开汽车 [kāi qìchē] — управлять автомобилем; вести машину" },
    { id: 50, char: "看", pinyin: "kàn", translation: "смотреть; читать (про себя); навестить", example: "看电影 [kàn diànyǐng] — смотреть кино [фильм]; 看朋友 [kàn péngyou] — навестить друга" },
    { id: 51, char: "看见", pinyin: "kànjiàn", translation: "увидеть; видеть", example: "看不见 [kànbùjiàn] — нельзя рассмотреть; не видно" },
    { id: 52, char: "块", pinyin: "kuài", translation: "сч. сл. для основных денежных единиц; кусок; глыба", example: "一块卢布 [yī kuài lúbù] — один рубль" },
    { id: 53, char: "来", pinyin: "lái", translation: "приходить; прибывать; приезжать", example: "请他来 [qǐng tā lái] — попроси его прийти; 来了一个代表团 [láile yīge dàibiǎotuán] — прибыла [приехала] делегация" },
    { id: 54, char: "老师", pinyin: "lǎoshī", translation: "учитель; преподаватель", example: "" },
    { id: 55, char: "了", pinyin: "le", translation: "глагольный суффикс завершенности действия", example: "我写了信就来 [wǒ xiěle xìn jiù lái] — я напишу письмо и приду" },
    { id: 56, char: "冷", pinyin: "lěng", translation: "холодный; холодно; холод", example: "外面很冷 [wàimian hěn lěng] — на улице очень холодно" },
    { id: 57, char: "里", pinyin: "lǐ", translation: "внутри; в", example: "皮箱里 [píxiānglǐ] — в чемодане; 屋子里 [wūzilǐ] — в комнате" },
    { id: 58, char: "零", pinyin: "líng", translation: "ноль; нолевой", example: "零下五度 [língxià wǔdù] — пять градусов ниже нуля; 零三号 [yī líng sān hào] — №103" },
    { id: 59, char: "六", pinyin: "liù", translation: "шесть; шестой", example: "" },
    { id: 60, char: "妈妈", pinyin: "māma", translation: "мама", example: "" },
    { id: 61, char: "吗", pinyin: "ma", translation: "фразовая частица, выражающая вопрос", example: "他来了吗? [tā láile ma] — он пришёл?; 这件事吗, 其实不能怪他 [zhèjiàn shì ma, qíshí bùnéng guài tā] — в этом-то он, по сути дела, и не виноват; в этом его, как раз, винить и нельзя" },
    { id: 62, char: "买", pinyin: "mǎi", translation: "покупать, приобретать", example: "买东西 [mǎidōngxi] — покупать вещи; делать покупки" },
    { id: 63, char: "猫", pinyin: "māo", translation: "кошка", example: "" },
    { id: 64, char: "没", pinyin: "méi", translation: "отрицательная частица", example: "他昨天没来过 [tā zuótiān méi láiguo] — он вчера не приходил" },
    { id: 65, char: "没关系", pinyin: "méi guānxi", translation: "неважно; ничего; пустяки", example: "" },
    { id: 66, char: "米饭", pinyin: "mǐfàn", translation: "варёный рис", example: "" },
    { id: 67, char: "明天", pinyin: "míngtiān", translation: "завтра; завтрашний день", example: "明天见! [míngtiānjiàn] — до завтра!; завтра увидимся" },
    { id: 68, char: "名字", pinyin: "míngzi", translation: "имя (человека); кличка (животного)", example: "" },
    { id: 69, char: "哪", pinyin: "nǎ", translation: "какой; который", example: "你学的是哪一国语言? [nǐ xuéde shì nǎ yī guó yǔyán] — какой иностранный язык вы изучаете?" },
    { id: 70, char: "那", pinyin: "nà", translation: "тот; то; тогда, в таком случае", example: "那棵树 [nàkē shù] — то дерево; 那是他的东西 [nà shì tāde dōngxi] — то — его вещи" },
    { id: 71, char: "呢", pinyin: "ne", translation: "фразовая частица, выражающая вопрос же?", example: "你们看什么呢? [nǐmen kàn shénme ne] — что же вы смотрите?; 你呢 [nǐ ne] — а ты?" },
    { id: 72, char: "能", pinyin: "néng", translation: "способный; способность", example: "无能 [wúnéng] — неспособный; бесталанный" },
    { id: 73, char: "你", pinyin: "nǐ", translation: "ты; вы; твой; ваш", example: "他不认识你 [tā bù rènshi nǐ] — он не знает тебя [Вас]; он с тобой [с Вами] не знаком" },
    { id: 74, char: "年", pinyin: "nián", translation: "год; годы", example: "今年 [jīnnián] — текущий год; в текущем году; 近年来 [jìnnián lái] — (за) последние годы" },
    { id: 75, char: "女儿", pinyin: "nǚ'ér", translation: "дочь", example: "" },
    { id: 76, char: "朋友", pinyin: "péngyou", translation: "друг, товарищ; друзья", example: "" },
    { id: 77, char: "漂亮", pinyin: "piàoliang", translation: "красивый", example: "" },
    { id: 78, char: "苹果", pinyin: "píngguǒ", translation: "яблоко", example: "" },
    { id: 79, char: "七", pinyin: "qī", translation: "семь; седьмой", example: "" },
    { id: 80, char: "钱", pinyin: "qián", translation: "деньги", example: "花钱 [huā qián] — тратить деньги; 有钱的人 [yǒu qián de rén] — богатый человек" },
    { id: 81, char: "前面", pinyin: "qiánmiàn", translation: "перед; передний; впереди; перед; выше; ранее", example: "前面所说的 [qiánmiàn suǒshuōde] — вышесказанное" },
    { id: 82, char: "请", pinyin: "qǐng", translation: "просить; пожалуйста!; приглашать", example: "请坐 [qǐng zuò] — садитесь, пожалуйста; 请医生 [qǐng yīshēng] — пригласить врача" },
    { id: 83, char: "去", pinyin: "qù", translation: "уходить; отправляться; идти", example: "你上那儿去? [nǐ shàng nǎr qù] — Куда ты идёшь?; 他开会去了 [tā kāihuì qùle] — он пошёл на собрание" },
    { id: 84, char: "热", pinyin: "rè", translation: "горячий; увлечение; мода", example: "熱茶 [rè chá] — горячий чай; 旅游热 [lǚyóurè] — туристский бум" },
    { id: 85, char: "人", pinyin: "rén", translation: "человек; люди", example: "年轻人 [niánqīngrén] — молодой человек; 自己人 [zìjǐrén] — свой человек; свои люди" },
    { id: 86, char: "认识", pinyin: "rènshi", translation: "знать; быть знакомым; знакомиться", example: "" },
    { id: 87, char: "日", pinyin: "rì", translation: "солнце; солнечный; день; число, дата", example: "日出 [rìchū] — восход солнца; 日报 [rìbào] — ежедневная газета" },
    { id: 88, char: "三", pinyin: "sān", translation: "три; третий", example: "三个人 [sāngè rén] — три человека" },
    { id: 89, char: "商店", pinyin: "shāngdiàn", translation: "магазин", example: "" },
    { id: 90, char: "上", pinyin: "shàng", translation: "верх; прошлый; на; в", example: "上衣 [shàngyī] — верхняя одежда; 上次 [shàngcì] — (в) прошлый раз" },
    { id: 91, char: "上午", pinyin: "shàngwǔ", translation: "до полудня", example: "" },
    { id: 92, char: "少", pinyin: "shǎo", translation: "мало; немного; редко", example: "我的行李很少 [wǒde xíngli hěn shǎo] — багажа у меня очень мало; 他很少迟到 [tā hěn shǎo chídào] — он очень редко опаздывает" },
    { id: 93, char: "谁", pinyin: "shuí, shéi", translation: "кто; кого; чей", example: "谁来了? [shuí láile] — кто пришёл?" },
    { id: 94, char: "什么", pinyin: "shénme", translation: "что?, что такое?; какой?; как?", example: "" },
    { id: 95, char: "十", pinyin: "shí", translation: "десять; десятый", example: "十个人 [shígè rén] — десять человек" },
    { id: 96, char: "时候", pinyin: "shíhou", translation: "время, промежуток; времени; во время", example: "" },
    { id: 97, char: "是", pinyin: "shì", translation: "есть; быть; являться; да; правда", example: "我是工人 [wǒ shì gōngrén] — я рабочий; 他说得是 [tā shuōde shì] — он сказал правильно" },
    { id: 98, char: "书", pinyin: "shū", translation: "книга", example: "新书 [xīnshū] — новая книга" },
    { id: 99, char: "水", pinyin: "shuǐ", translation: "вода", example: "喝水 [hē shuǐ] — пить воду; 开水 [kāishuǐ] — кипячёная вода; кипяток" },
    { id: 100, char: "水果", pinyin: "shuǐguǒ", translation: "фрукты", example: "" },
    { id: 101, char: "睡觉", pinyin: "shuìjiào", translation: "спать", example: "" },
    { id: 102, char: "说话", pinyin: "shuōhuà", translation: "говорить", example: "" },
    { id: 103, char: "四", pinyin: "sì", translation: "четыре; четвёртый", example: "" },
    { id: 104, char: "岁", pinyin: "suì", translation: "годы, возраст", example: "" },
    { id: 105, char: "他", pinyin: "tā", translation: "он", example: "" },
    { id: 106, char: "她", pinyin: "tā", translation: "она", example: "" },
    { id: 107, char: "太", pinyin: "tài", translation: "слишком, чрезмерно", example: "太大 [tài dà] — слишком большой" },
    { id: 108, char: "天", pinyin: "tiān", translation: "день, небо", example: "今天 [jīntiān] — сегодня" },
    { id: 109, char: "听", pinyin: "tīng", translation: "слушать", example: "听音乐 [tīng yīnyuè] — слушать музыку" },
    { id: 110, char: "同学", pinyin: "tóngxué", translation: "одноклассник, однокурсник", example: "" },
    { id: 111, char: "喂", pinyin: "wèi", translation: "алло (при ответе на телефон)", example: "" },
    { id: 112, char: "我", pinyin: "wǒ", translation: "я, мой", example: "" },
    { id: 113, char: "我们", pinyin: "wǒmen", translation: "мы, наш", example: "" },
    { id: 114, char: "五", pinyin: "wǔ", translation: "пять; пятый", example: "五年级 [wǔ niánjí] — пятый курс [класс]" },
    { id: 115, char: "喜欢", pinyin: "xǐhuan", translation: "нравиться; любить", example: "" },
    { id: 116, char: "下", pinyin: "xià", translation: "нижний; низ; послелог под, при; следующий", example: "下嘴唇 [xià zuǐchún] — нижняя губа; 站在树下 [zhàn zài shù xià] — стоять под деревом; 下月 [xiàyuè] — будущий месяц" },
    { id: 117, char: "下午", pinyin: "xiàwǔ", translation: "вторая половина дня, после полудня", example: "" },
    { id: 118, char: "下雨", pinyin: "xiàyǔ", translation: "идёт дождь; стоит дождливая погода", example: "" },
    { id: 119, char: "先生", pinyin: "xiānsheng", translation: "господин; мистер", example: "" },
    { id: 120, char: "现在", pinyin: "xiànzài", translation: "теперь; сейчас; ныне", example: "" },
    { id: 121, char: "想", pinyin: "xiǎng", translation: "думать; собираться; хотеть", example: "想办法 [xiǎng bànfǎ] — изыскивать [обдумывать] методы [способы]; 我也想试试 [wǒ yě xiǎng shìshì] — я тоже хочу попробовать" },
    { id: 122, char: "小", pinyin: "xiǎo", translation: "маленький; мелкий; малый; молодой; младший", example: "这间房间太小 [zhèjiān fángjiān tài xiǎo] — эта комната слишком маленькая; 他比我小一岁 [tā bǐ wǒ xiǎo yīsuì] — он моложе меня на один год" },
    { id: 123, char: "小姐", pinyin: "xiǎojiě", translation: "барышня; мисс", example: "" },
    { id: 124, char: "些", pinyin: "xiē", translation: "немного, несколько", example: "你快些走 [nǐ kuài xiē zǒu] — иди побыстрее; 这些 [zhèxiē] — эти (несколько)" },
    { id: 125, char: "写", pinyin: "xiě", translation: "писать; записывать; описывать", example: "写信 [xiě xìn] — писать письмо; 写小说 [xiě xiǎoshuō] — писать рассказ" },
    { id: 126, char: "谢谢", pinyin: "xièxie", translation: "спасибо, благодарю; благодарить", example: "" },
    { id: 127, char: "星期", pinyin: "xīngqī", translation: "неделя", example: "今天星期几? [jīntiān xīngqī jǐ] — какой сегодня день недели?" },
    { id: 128, char: "学生", pinyin: "xuéshēng", translation: "студент; ученик; учащийся", example: "学生证 [xuéshēng zhèng] — студенческий билет" },
    { id: 129, char: "学习", pinyin: "xuéxí", translation: "учиться; обучаться; обучение, учёба", example: "" },
    { id: 130, char: "学校", pinyin: "xuéxiào", translation: "школа; учебное заведение; училище", example: "" },
    { id: 131, char: "一", pinyin: "yī", translation: "один; единица; первый", example: "一次 [yīcì] — один раз; 一年 [yī nián] — один год" },
    { id: 132, char: "衣服", pinyin: "yīfu", translation: "одежда; платье; костюм", example: "" },
    { id: 133, char: "医生", pinyin: "yīshēng", translation: "врач, доктор", example: "" },
    { id: 134, char: "医院", pinyin: "yīyuàn", translation: "больница; госпиталь", example: "" },
    { id: 135, char: "椅子", pinyin: "yǐzi", translation: "стул", example: "" },
    { id: 136, char: "有", pinyin: "yǒu", translation: "иметь(ся); иметь в наличии; обладать; есть", example: "我没有工夫 [wǒ méi yǒu gōngfu] — у меня нет свободного времени; 有这种可能 [yǒu zhè zhǒng kěnéng] — имеется [есть] такая возможность" },
    { id: 137, char: "月", pinyin: "yuè", translation: "луна; месяц", example: "上月 [shàngyuè] — прошлый месяц; 月票 [yuèpiào] — месячный (проездной) билет" },
    { id: 138, char: "在", pinyin: "zài", translation: "быть в живых; существовать; находиться; в; на", example: "他的祖父还在 [tāde zǔfù hái zài] — его дед ещё жив; 书在桌子上 [shū zài zhuōzi shang] — книга (находится) на столе; 他们在礼堂开会 [tāmen zài lǐtáng kāihuì] — они проводят собрание в актовом зале" },
    { id: 139, char: "再见", pinyin: "zàijiàn", translation: "до свидания", example: "" },
    { id: 140, char: "怎么", pinyin: "zěnme", translation: "как?, каким образом?", example: "" },
    { id: 141, char: "怎么样", pinyin: "zěnmeyàng", translation: "как, каким образом; каков", example: "" },
    { id: 142, char: "这", pinyin: "zhè", translation: "это, этот", example: "这是谁? [zhè shì shuí] — кто это?; 这小孩 [zhè xiǎohái] — этот ребёнок" },
    { id: 143, char: "中国", pinyin: "zhōngguó", translation: "Китай; китайский", example: "中国话 [zhōngguóhuà] — китайский язык" },
    { id: 144, char: "中午", pinyin: "zhōngwǔ", translation: "полдень", example: "" },
    { id: 145, char: "住", pinyin: "zhù", translation: "жить, проживать", example: "我家住在城外 [wǒ jiā zhù zài chéng wài] — моя семья живёт за городом; 记住 [jìzhù] — запомнить; 站住! [zhànzhù] — стой! (команда)" },
    { id: 146, char: "桌子", pinyin: "zhuōzi", translation: "стол", example: "书桌 [shūzhuō] — письменный стол" },
    { id: 147, char: "字", pinyin: "zì", translation: "иероглиф; слово", example: "汉字 [hànzì] — китайские иероглифы; 常用字 [chángyòngzì] — наиболее употребительные иероглифы" },
    { id: 148, char: "昨天", pinyin: "zuótiān", translation: "вчера; вчерашний день", example: "" },
    { id: 149, char: "坐", pinyin: "zuò", translation: "сидеть; садиться; ехать на [в]", example: "请坐! [qǐng zuò] — садитесь, пожалуйста!; 坐火车 [zuò huǒchē] — ехать на поезде" },
    { id: 150, char: "做", pinyin: "zuò", translation: "делать; изготавливать; быть [работать] кем-либо; писать", example: "你在做什么? [nǐ zài zuò shénme] — что ты делаешь?; 做教员 [zuò jiàoyuán] — работать преподавателем" }
];