// Массив 300 НОВЫХ слов для HSK 3 (слов, которых нет в HSK 2)
const hsk3NewWords = [
    { id: 301, char: "阿姨", pinyin: "āyí", translation: "тётя, тётка; няня (в детском саду)", example: "阿姨好 [āyí hǎo] — здравствуйте, тётя" },
    { id: 302, char: "啊", pinyin: "a", translation: "фразовая частица восклицательных предложений", example: "别忙啊 ! [bié máng a] — не торопитесь!" },
    { id: 303, char: "矮", pinyin: "ǎi", translation: "низкорослый, низкий", example: "几棵矮树 [jǐkē ǎi shù] — несколько низкорослых деревьев" },
    { id: 304, char: "爱好", pinyin: "àihào", translation: "хобби, увлечение", example: "爱好音乐 [àihào yīnyùe] — любить музыку" },
    { id: 305, char: "安静", pinyin: "ānjìng", translation: "покойный; тихий; покой", example: "病人需要安静 [bìngrén xūyào ānjìng] — больной нуждается в покое" },
    { id: 306, char: "把", pinyin: "bǎ", translation: "держать; сч. слово для предметов с ручкой", example: "把书拿来 [bǎ shū nálai] — принести книгу" },
    { id: 307, char: "班", pinyin: "bān", translation: "группа; класс", example: "学班 [xuébān] — учебная группа" },
    { id: 308, char: "搬", pinyin: "bān", translation: "передвигать; переносить", example: "搬行李 [bān xíngli] — переносить багаж" },
    { id: 309, char: "半", pinyin: "bàn", translation: "половина; полу-", example: "两斤半 [liǎngjīn bàn] — два цзиня с половиной" },
    { id: 310, char: "办法", pinyin: "bànfǎ", translation: "способ, метод", example: "有办法 [yǒu bànfǎ] — есть выход" },
    { id: 311, char: "办公室", pinyin: "bàngōngshì", translation: "кабинет; офис", example: "" },
    { id: 312, char: "饱", pinyin: "bǎo", translation: "насытиться; досыта", example: "我已经饱了 [wǒ yǐjing bǎole] — я уже сыт" },
    { id: 313, char: "北方", pinyin: "běifāng", translation: "север; северный", example: "" },
    { id: 314, char: "被", pinyin: "bèi", translation: "сч. слово для выражения пассива", example: "树被风刮倒了 [shù bèi fēng guādǎle] — дерево повалено ветром" },
    { id: 315, char: "鼻子", pinyin: "bízi", translation: "нос", example: "" },
    { id: 316, char: "表示", pinyin: "biǎoshì", translation: "выражать; высказывать", example: "表示不安 [biǎoshì bù'ān] — выразить обеспокоенность" },
    { id: 317, char: "表演", pinyin: "biǎoyǎn", translation: "исполнять; играть (на сцене)", example: "" },
    { id: 318, char: "宾馆", pinyin: "bīnguǎn", translation: "гостиница", example: "" },
    { id: 319, char: "冰箱", pinyin: "bīngxiāng", translation: "холодильник", example: "" },
    { id: 320, char: "才", pinyin: "cái", translation: "только, только что", example: "我今天才来 [wǒ jīntiān cái lái] — я прибыл только сегодня" },
    { id: 321, char: "菜单", pinyin: "càidān", translation: "меню", example: "" },
    { id: 322, char: "参加", pinyin: "cānjiā", translation: "участвовать; принимать участие", example: "" },
    { id: 323, char: "草", pinyin: "cǎo", translation: "трава; солома", example: "青草 [qīngcǎo] — трава" },
    { id: 324, char: "层", pinyin: "céng", translation: "слой; ярус; этаж", example: "七层大楼 [qī céng dàlóu] — семиэтажный дом" },
    { id: 325, char: "差", pinyin: "chā", translation: "разница; отличаться", example: "时差 [shíchā] — разница во времени" },
    { id: 326, char: "长", pinyin: "zhǎng", translation: "расти; вырасти", example: "长得好 [zhǎngde hǎo] — хорошо расти" },
    { id: 327, char: "超市", pinyin: "chāoshì", translation: "супермаркет", example: "" },
    { id: 328, char: "衬衫", pinyin: "chènshān", translation: "рубашка, сорочка", example: "" },
    { id: 329, char: "成绩", pinyin: "chéngjī", translation: "успехи; достижения", example: "" },
    { id: 330, char: "城市", pinyin: "chéngshì", translation: "город; городской", example: "城市建设 [chéngshì jiànshè] — городское строительство" },
    { id: 331, char: "迟到", pinyin: "chídào", translation: "опоздать", example: "" },
    { id: 332, char: "出现", pinyin: "chūxiàn", translation: "появиться; возникнуть", example: "" },
    { id: 333, char: "厨房", pinyin: "chúfáng", translation: "кухня", example: "" },
    { id: 334, char: "除了", pinyin: "chúle", translation: "кроме; помимо", example: "" },
    { id: 335, char: "春", pinyin: "chūn", translation: "весна; весенний", example: "春风 [chūnfēng] — весенний ветер" },
    { id: 336, char: "词语", pinyin: "cíyǔ", translation: "обороты речи; выражения", example: "方言词语 [fāngyán cíyǔ] — диалектизм" },
    { id: 337, char: "聪明", pinyin: "cōngming", translation: "умный; способный", example: "" },
    { id: 338, char: "打扫", pinyin: "dǎsǎo", translation: "подметать; убирать", example: "" },
    { id: 339, char: "打算", pinyin: "dǎsuan", translation: "рассчитывать, намереваться", example: "" },
    { id: 340, char: "带", pinyin: "dài", translation: "иметь при себе; захватить", example: "带雨伞 [dài yǔsǎn] — иметь при себе зонтик" },
    { id: 341, char: "担心", pinyin: "dānxīn", translation: "беспокоиться, тревожиться", example: "" },
    { id: 342, char: "蛋糕", pinyin: "dàngāo", translation: "пирожное, бисквит", example: "" },
    { id: 343, char: "当然", pinyin: "dāngrán", translation: "конечно, естественно", example: "" },
    { id: 344, char: "地", pinyin: "de", translation: "показатель обстоятельства образа действия", example: "认真地工作 [rènzhēn de gōngzuò] — работать серьёзно" },
    { id: 345, char: "灯", pinyin: "dēng", translation: "лампа; фонарь", example: "台灯 [táidēng] — настольная лампа" },
    { id: 346, char: "低", pinyin: "dī", translation: "низкий; низко", example: "低飞 [dīfēi] — низко лететь" },
    { id: 347, char: "地方", pinyin: "dìfāng", translation: "периферия; места; местный", example: "地方自治 [dìfāng zìzhì] — местное самоуправление" },
    { id: 348, char: "地铁", pinyin: "dìtiě", translation: "метро, метрополитен", example: "" },
    { id: 349, char: "地图", pinyin: "dìtú", translation: "карта (географическая)", example: "" },
    { id: 350, char: "电子邮件", pinyin: "diànzǐ yóujiàn", translation: "электронная почта, E-mail", example: "" },
    { id: 351, char: "冬", pinyin: "dōng", translation: "зима; зимний", example: "过冬 [guò dōng] — пережить зиму" },
    { id: 352, char: "动物", pinyin: "dòngwù", translation: "животное; животный", example: "动物油 [dòngwùyóu] — животные жиры" },
    { id: 353, char: "短", pinyin: "duǎn", translation: "короткий; краткий", example: "短距离 [duǎn jùlí] — короткое расстояние" },
    { id: 354, char: "段", pinyin: "duàn", translation: "отрезок; кусок; часть", example: "一段管子 [yīduàn guǎnzi] — кусок трубы" },
    { id: 355, char: "锻炼", pinyin: "duànliàn", translation: "закаливать; закалка", example: "锻炼身体 [duànliàn shēntǐ] — закаляться" },
    { id: 356, char: "发烧", pinyin: "fāshāo", translation: "температурить; температура", example: "" },
    { id: 357, char: "发现", pinyin: "fāxiàn", translation: "обнаружить; заметить", example: "" },
    { id: 358, char: "方便", pinyin: "fāngbiàn", translation: "удобный; удобство", example: "" },
    { id: 359, char: "放", pinyin: "fàng", translation: "отпускать; выпускать; ставить", example: "放孩子们出去玩 [fàng háizimen chūqu wán] — отпустить детей погулять" },
    { id: 360, char: "分", pinyin: "fēn", translation: "делить(ся); минута", example: "分土地 [fēn tǔdì] — делить землю" },
    { id: 361, char: "干净", pinyin: "gānjìng", translation: "чистый; опрятный", example: "" },
    { id: 362, char: "敢", pinyin: "gǎn", translation: "сметь; осмелиться", example: "敢说实话 [gǎn shuō shíhuà] — смочь сказать правду" },
    { id: 363, char: "感冒", pinyin: "gǎnmào", translation: "простудиться; простудное заболевание", example: "流行性感冒 [liúxíngxìng gǎnmào] — грипп" },
    { id: 364, char: "刚才", pinyin: "gāngcái", translation: "только что", example: "" },
    { id: 365, char: "根据", pinyin: "gēnjù", translation: "согласно; на основании", example: "" },
    { id: 366, char: "更", pinyin: "gèng", translation: "ещё; ещё более", example: "更少 [gèngshǎo] — ещё меньше" },
    { id: 367, char: "公园", pinyin: "gōngyuán", translation: "парк", example: "" },
    { id: 368, char: "故事", pinyin: "gùshì", translation: "сказание; сказка; рассказ", example: "" },
    { id: 369, char: "刮风", pinyin: "guāfēng", translation: "дует ветер; ветрено", example: "" },
    { id: 370, char: "关", pinyin: "guān", translation: "закрывать; выключать", example: "关门 [guānmén] — закрыть дверь" },
    { id: 371, char: "关系", pinyin: "guānxi", translation: "связь; отношение", example: "国际关系 [guójì guānxi] — международные отношения" },
    { id: 372, char: "关于", pinyin: "guānyú", translation: "относительно, в отношении", example: "" },
    { id: 373, char: "国家", pinyin: "guójiā", translation: "государство; страна", example: "国家制度 [guójiā zhìdù] — государственный строй" },
    { id: 374, char: "果汁", pinyin: "guǒzhī", translation: "фруктовый сок", example: "" },
    { id: 375, char: "过去", pinyin: "guòqù", translation: "проходить; миновать", example: "" },
    { id: 376, char: "过", pinyin: "guo", translation: "глагольный суффикс завершённо-многократного вида", example: "到过 [dàoguo] — бывал где-либо" },
    { id: 377, char: "害怕", pinyin: "hàipà", translation: "бояться; трусить", example: "" },
    { id: 378, char: "黑板", pinyin: "hēibǎn", translation: "классная доска", example: "" },
    { id: 379, char: "花", pinyin: "huā", translation: "цветок; тратить", example: "献花 [xiàn huā] — подарить цветы" },
    { id: 380, char: "花园", pinyin: "huāyuán", translation: "сад", example: "" },
    { id: 381, char: "画", pinyin: "huà", translation: "картина; рисовать", example: "铅笔画 [qiānbǐhuà] — рисунок карандашом" },
    { id: 382, char: "环境", pinyin: "huánjìng", translation: "окружение; окружающая среда", example: "" },
    { id: 383, char: "黄", pinyin: "huáng", translation: "жёлтый; желтеть", example: "黄叶 [huángyè] — жёлтые листья" },
    { id: 384, char: "会议", pinyin: "huìyì", translation: "собрание; конференция", example: "会议室 [huìyìshì] — зал заседаний" },
    { id: 385, char: "或者", pinyin: "huòzhě", translation: "или, либо", example: "" },
    { id: 386, char: "机场", pinyin: "jīchǎng", translation: "аэродром", example: "军用机场 [jūnyòng jīchǎng] — военный аэродром" },
    { id: 387, char: "机会", pinyin: "jīhuì", translation: "удобный случай, возможность", example: "错过机会 [cuòguò jīhuì] — упустить удобный случай" },
    { id: 388, char: "极", pinyin: "jí", translation: "наивысшая точка; крайность", example: "" },
    { id: 389, char: "记得", pinyin: "jìde", translation: "помнить", example: "" },
    { id: 390, char: "季节", pinyin: "jìjié", translation: "сезон; пора", example: "季节工 [jìjiégōng] — сезонный рабочий" },
    { id: 391, char: "检查", pinyin: "jiǎnchá", translation: "проверять; контролировать", example: "检查护照 [jiǎnchá hùzhào] — проверка паспортов" },
    { id: 392, char: "简单", pinyin: "jiǎndān", translation: "простой; примитивный", example: "" },
    { id: 393, char: "健康", pinyin: "jiànkāng", translation: "здоровье", example: "" },
    { id: 394, char: "见面", pinyin: "jiànmiàn", translation: "встретиться; увидеться", example: "" },
    { id: 395, char: "讲", pinyin: "jiǎng", translation: "говорить; рассказывать", example: "讲故事 [jiǎng gùshi] — рассказывать истории" },
    { id: 396, char: "教", pinyin: "jiāo", translation: "обучать; преподавать", example: "教识字 [jiāo shízì] — обучать грамоте" },
    { id: 397, char: "角", pinyin: "jiǎo", translation: "рог; угол", example: "鹿角 [lùjiǎo] — оленьи рога" },
    { id: 398, char: "脚", pinyin: "jiǎo", translation: "нога, ступня", example: "右脚 [yòujiǎo] — правая нога" },
    { id: 399, char: "接", pinyin: "jiē", translation: "получать; принимать; соединять", example: "接信 [jiēxìn] — получить письмо" },
    { id: 400, char: "街道", pinyin: "jiēdào", translation: "улица; уличный", example: "" },
    { id: 401, char: "结婚", pinyin: "jiéhūn", translation: "вступить в брак; жениться", example: "" },
    { id: 402, char: "结束", pinyin: "jiéshù", translation: "закончить(ся); завершить", example: "" },
    { id: 403, char: "节目", pinyin: "jiémù", translation: "номер (программы); программа", example: "节目单 [jiémùdān] — программа" },
    { id: 404, char: "节日", pinyin: "jiérì", translation: "праздник", example: "" },
    { id: 405, char: "解决", pinyin: "jiějué", translation: "решать, разрешать", example: "" },
    { id: 406, char: "经常", pinyin: "jīngcháng", translation: "постоянный; обычный", example: "" },
    { id: 407, char: "经过", pinyin: "jīngguò", translation: "проходить; через", example: "" },
    { id: 408, char: "经理", pinyin: "jīnglǐ", translation: "директор; управляющий", example: "" },
    { id: 409, char: "久", pinyin: "jiǔ", translation: "долго; давно", example: "很久没有见面 [hěnjiǔ méiyǒu jiànmiàn] — давно не виделись" },
    { id: 410, char: "旧", pinyin: "jiù", translation: "старый; прежний", example: "旧友 [jiùyǒu] — старый друг" },
    { id: 411, char: "举行", pinyin: "jǔxíng", translation: "проводить; устраивать", example: "举行会谈 [jǔxíng huìtǎn] — вести переговоры" },
    { id: 412, char: "句子", pinyin: "jùzi", translation: "предложение; фраза", example: "" },
    { id: 413, char: "决定", pinyin: "juédìng", translation: "решить; определить", example: "" },
    { id: 414, char: "渴", pinyin: "kě", translation: "испытывать жажду; жажда", example: "解渴 [jiěkě] — утолить жажду" },
    { id: 415, char: "可爱", pinyin: "kě'ài", translation: "достойный любви; милый", example: "" },
    { id: 416, char: "刻", pinyin: "kè", translation: "четверть часа; вырезать", example: "两点一刻 [liǎngdiǎn yīkè] — четверть третьего" },
    { id: 417, char: "客人", pinyin: "kèrén", translation: "гость; приглашённый", example: "" },
    { id: 418, char: "空调", pinyin: "kōngtiáo", translation: "кондиционер", example: "" },
    { id: 419, char: "口", pinyin: "kǒu", translation: "рот; устный", example: "一家三口人 [yī jiā sānkǒu rén] — семья из трёх человек" },
    { id: 420, char: "哭", pinyin: "kū", translation: "плакать; оплакивать", example: "哭起来 [kūqilai] — расплакаться" },
    { id: 421, char: "裤子", pinyin: "kùzi", translation: "брюки", example: "" },
    { id: 422, char: "筷子", pinyin: "kuàizi", translation: "куайцзы, палочки для еды", example: "" },
    { id: 423, char: "蓝", pinyin: "lán", translation: "синий", example: "蓝天 [lántiān] — синее небо" },
    { id: 424, char: "老", pinyin: "lǎo", translation: "старый; уважаемый", example: "老人 [lǎorén] — старый человек" },
    { id: 425, char: "脸", pinyin: "liǎn", translation: "лицо", example: "洗脸 [xǐ liǎn] — умываться" },
    { id: 426, char: "练习", pinyin: "liànxí", translation: "тренироваться; упражнение", example: "练习本 [liànxíběn] — тетрадь для упражнений" },
    { id: 427, char: "辆", pinyin: "liàng", translation: "сч. сл. для колёсного транспорта", example: "三辆汽车 [sānliàng qìchē] — три автомобиля" },
    { id: 428, char: "了解", pinyin: "liǎojiě", translation: "понять; уразуметь", example: "" },
    { id: 429, char: "邻居", pinyin: "línjū", translation: "сосед", example: "" },
    { id: 430, char: "楼", pinyin: "lóu", translation: "здание; дом; этаж", example: "办公楼 [bàngōnglóu] — административное здание" },
    { id: 431, char: "绿", pinyin: "lǜ", translation: "зелёный", example: "绿草 [lǜcǎo] — зелёная трава" },
    { id: 432, char: "马", pinyin: "mǎ", translation: "лошадь; конь", example: "骑马 [qǐmǎ] — ехать верхом на лошади" },
    { id: 433, char: "马上", pinyin: "mǎshàng", translation: "тотчас, немедленно", example: "" },
    { id: 434, char: "满意", pinyin: "mǎnyì", translation: "быть довольным; довольный", example: "" },
    { id: 435, char: "帽子", pinyin: "màozi", translation: "головной убор; шапка", example: "" },
    { id: 436, char: "米", pinyin: "mǐ", translation: "рис (очищенный); метр", example: "米粉 [mǐfěn] — рисовая мука" },
    { id: 437, char: "面包", pinyin: "miànbāo", translation: "хлеб; булка", example: "" },
    { id: 438, char: "面条", pinyin: "miàntiáo", translation: "лапша", example: "" },
    { id: 439, char: "明白", pinyin: "míngbai", translation: "понимать; понятный", example: "明白人 [míngbairén] — разумный человек" },
    { id: 440, char: "拿", pinyin: "ná", translation: "брать; взять; держать", example: "手里拿着一把扇子 [shǒuli názhe yī bǎ shànzi] — держать в руке веер" },
    { id: 441, char: "奶奶", pinyin: "nǎinai", translation: "бабушка", example: "" },
    { id: 442, char: "南", pinyin: "nán", translation: "юг; южный", example: "南风 [nánfēng] — южный ветер" },
    { id: 443, char: "难", pinyin: "nán", translation: "трудный; трудно", example: "难说 [nánshuō] — трудно сказать" },
    { id: 444, char: "难过", pinyin: "nánguò", translation: "трудно [тяжело] жить", example: "" },
    { id: 445, char: "努力", pinyin: "nǔlì", translation: "прилагать усилия; стараться", example: "努力学习 [nǔlì xuéxí] — старательно учиться" },
    { id: 446, char: "爬山", pinyin: "páshān", translation: "восходить на горы; альпинизм", example: "" },
    { id: 447, char: "盘子", pinyin: "pánzi", translation: "тарелка; блюдо", example: "" },
    { id: 448, char: "胖", pinyin: "pàng", translation: "толстый; полный", example: "他胖了好多 [tā pàngle hǎoduō] — он сильно располнел" },
    { id: 449, char: "啤酒", pinyin: "píjiǔ", translation: "пиво", example: "" },
    { id: 450, char: "葡萄", pinyin: "pútao", translation: "виноград", example: "葡萄酒 [pútaojiǔ] — виноградное вино" },
    { id: 451, char: "普通话", pinyin: "pǔtōnghuà", translation: "путунхуа", example: "" },
    { id: 452, char: "其实", pinyin: "qíshí", translation: "по сути дела; фактически", example: "" },
    { id: 453, char: "其他", pinyin: "qítā", translation: "прочие; другие", example: "" },
    { id: 454, char: "骑", pinyin: "qí", translation: "сидеть верхом; ехать", example: "骑马 [qí mǎ] — ехать верхом" },
    { id: 455, char: "奇怪", pinyin: "qíguài", translation: "удивительный; странный", example: "" },
    { id: 456, char: "铅笔", pinyin: "qiānbǐ", translation: "карандаш", example: "" },
    { id: 457, char: "清楚", pinyin: "qīngchu", translation: "ясный; отчётливый", example: "" },
    { id: 458, char: "秋", pinyin: "qiū", translation: "осень; осенний", example: "秋风 [qiūfēng] — осенний ветер" },
    { id: 459, char: "裙子", pinyin: "qúnzi", translation: "юбка", example: "" },
    { id: 460, char: "然后", pinyin: "ránhòu", translation: "потом, затем", example: "" },
    { id: 461, char: "热情", pinyin: "rèqíng", translation: "энтузиазм; пыл", example: "" },
    { id: 462, char: "认为", pinyin: "rènwéi", translation: "полагать, считать", example: "" },
    { id: 463, char: "认真", pinyin: "rènzhēn", translation: "серьёзный; добросовестный", example: "" },
    { id: 464, char: "容易", pinyin: "róngyì", translation: "лёгкий; легко", example: "这件事并不容易 [zhèjiàn shì bìngbù róngyì] — это дело совсем не лёгкое" },
    { id: 465, char: "如果", pinyin: "rúguǒ", translation: "если; если бы", example: "" },
    { id: 466, char: "伞", pinyin: "sǎn", translation: "зонтик; зонт", example: "折伞 [zhésǎn] — складной зонтик" },
    { id: 467, char: "上网", pinyin: "shàngwǎng", translation: "зайти в интернет", example: "" },
    { id: 468, char: "生气", pinyin: "shēngqì", translation: "сердиться; гневаться", example: "" },
    { id: 469, char: "声音", pinyin: "shēngyīn", translation: "звук; звучание", example: "" },
    { id: 470, char: "使", pinyin: "shǐ", translation: "использовать; применять", example: "使化肥 [shǐ huàféi] — применять удобрения" },
    { id: 471, char: "世界", pinyin: "shìjiè", translation: "вселенная; мир", example: "世界市场 [shìjiè shìchǎng] — мировой рынок" },
    { id: 472, char: "瘦", pinyin: "shòu", translation: "худой; худеть", example: "他瘦了 [tā shòule] — он похудел" },
    { id: 473, char: "舒服", pinyin: "shūfu", translation: "удобный; уютный", example: "不舒服 [bù shūfu] — нездоровиться" },
    { id: 474, char: "叔叔", pinyin: "shūshu", translation: "дядя (младший брат отца)", example: "" },
    { id: 475, char: "树", pinyin: "shù", translation: "дерево", example: "一棵树 [yīkē shù] — одно дерево" },
    { id: 476, char: "数学", pinyin: "shùxué", translation: "математика", example: "" },
    { id: 477, char: "刷牙", pinyin: "shuāyá", translation: "чистка зубов", example: "" },
    { id: 478, char: "双", pinyin: "shuāng", translation: "пара; два; оба", example: "双皮鞋 [yī shuāng píxié] — пара ботинок" },
    { id: 479, char: "水平", pinyin: "shuǐpíng", translation: "уровень; горизонтальный", example: "生活水平 [shēnghuó shuǐpíng] — уровень жизни" },
    { id: 480, char: "司机", pinyin: "sījī", translation: "машинист; шофёр", example: "" },
    { id: 481, char: "虽然", pinyin: "suīrán", translation: "хотя, хоть", example: "" },
    { id: 482, char: "太阳", pinyin: "tàiyáng", translation: "солнце; солнечный", example: "太阳能 [tàiyángnéng] — солнечная энергия" },
    { id: 483, char: "糖", pinyin: "táng", translation: "сахар, сладость", example: "蔗糖 [zhètáng] — тростниковый сахар" },
    { id: 484, char: "特别", pinyin: "tèbié", translation: "особый; специфический", example: "" },
    { id: 485, char: "疼", pinyin: "téng", translation: "больно; болеть", example: "头疼 [tóuténg] — головная боль" },
    { id: 486, char: "提高", pinyin: "tígāo", translation: "поднять; повысить", example: "提高工资 [tígāo gōngzī] — повысить зарплату" },
    { id: 487, char: "体育", pinyin: "tǐyù", translation: "физкультура; спорт", example: "体育场 [tǐyùchǎng] — спортплощадка" },
    { id: 488, char: "甜", pinyin: "tián", translation: "сладкий; сладко", example: "这西瓜真甜 [zhè xīguā zhēn tián] — этот арбуз очень сладкий" },
    { id: 489, char: "条", pinyin: "tiáo", translation: "сч. сл. для длинных предметов", example: "一条路 [yī tiáo lù] — одна дорога" },
    { id: 490, char: "同事", pinyin: "tóngshì", translation: "сослуживец, коллега", example: "" },
    { id: 491, char: "同意", pinyin: "tóngyì", translation: "согласиться; одобрить", example: "" },
    { id: 492, char: "头发", pinyin: "tóufa", translation: "волосы", example: "" },
    { id: 493, char: "突然", pinyin: "tūrán", translation: "вдруг, внезапно", example: "" },
    { id: 494, char: "图书馆", pinyin: "túshūguǎn", translation: "библиотека", example: "" },
    { id: 495, char: "腿", pinyin: "tuǐ", translation: "нога; бедро", example: "大腿 [dàtuǐ] — бедро" },
    { id: 496, char: "完成", pinyin: "wánchéng", translation: "закончить(ся); завершить", example: "完成体 [wánchéngtǐ] — совершенный вид" },
    { id: 497, char: "碗", pinyin: "wǎn", translation: "чашка; пиала", example: "茶碗 [cháwǎn] — чайная чашка" },
    { id: 498, char: "万", pinyin: "wàn", translation: "десять тысяч", example: "二十五万 [èrshí wǔ wàn] — двести пятьдесят тысяч" },
    { id: 499, char: "忘记", pinyin: "wàngjì", translation: "забывать", example: "" },
    { id: 500, char: "为", pinyin: "wèi", translation: "для, ради; за", example: "为人民服务 [wèi rénmín fúwù] — служить народу" },
    { id: 501, char: "文化", pinyin: "wénhuà", translation: "культура; цивилизация", example: "文化宫 [wénhuàgōng] — дворец культуры" },
    { id: 502, char: "西瓜", pinyin: "xīguā", translation: "арбуз", example: "" },
    { id: 503, char: "习惯", pinyin: "xíguàn", translation: "привычка; обычай", example: "" },
    { id: 504, char: "洗手间", pinyin: "xǐshǒujiān", translation: "туалет, уборная", example: "" },
    { id: 505, char: "夏", pinyin: "xià", translation: "лето; летний", example: "" },
    { id: 506, char: "先", pinyin: "xiān", translation: "раньше; сначала", example: "你先一个人去 [nǐ xiān yīge rén qù] — ты сначала сходи один" },
    { id: 507, char: "香蕉", pinyin: "xiāngjiāo", translation: "банан", example: "" },
    { id: 508, char: "相同", pinyin: "xiāngtóng", translation: "одинаковый; тождественный", example: "" },
    { id: 509, char: "相信", pinyin: "xiāngxìn", translation: "верить; доверять", example: "" },
    { id: 510, char: "像", pinyin: "xiàng", translation: "внешний облик; иметь сходство", example: "" },
    { id: 511, char: "小心", pinyin: "xiǎoxīn", translation: "остерегаться; осторожно", example: "小心油漆 ! [xiǎoxīn yóuqī] — осторожно, окрашено!" },
    { id: 512, char: "笑", pinyin: "xiào", translation: "смеяться; смех", example: "他笑起来了 [tā xiàoqilaile] — он рассмеялся" },
    { id: 513, char: "校长", pinyin: "xiàozhǎng", translation: "директор школы; ректор", example: "" },
    { id: 514, char: "鞋", pinyin: "xié", translation: "туфли; ботинки", example: "女鞋 [nǚxié] — женские туфли" },
    { id: 515, char: "新闻", pinyin: "xīnwén", translation: "новости; известия", example: "" },
    { id: 516, char: "新鲜", pinyin: "xīnxiān", translation: "свежий; чистый", example: "" },
    { id: 517, char: "信", pinyin: "xìn", translation: "верить; доверять; письмо", example: "我信他的话 [wǒ xìn tāde huà] — я верю ему" },
    { id: 518, char: "行李箱", pinyin: "xínglǐxiāng", translation: "чемодан", example: "" },
    { id: 519, char: "姓", pinyin: "xìng", translation: "фамилия", example: "你姓什么 ? [nǐ xìng shénme] — как ваша фамилия?" },
    { id: 520, char: "兴趣", pinyin: "xìngqù", translation: "интерес", example: "不感兴趣 [bùgǎn xìngqù] — не испытывать интереса" },
    { id: 521, char: "熊猫", pinyin: "xióngmāo", translation: "бамбуковый медведь; панда", example: "" },
    { id: 522, char: "需要", pinyin: "xūyào", translation: "требоваться; нуждаться", example: "" },
    { id: 523, char: "选择", pinyin: "xuǎnzé", translation: "выбирать; отбирать", example: "选择职业 [xuǎnzé zhíyè] — выбрать профессию" },
    { id: 524, char: "雪", pinyin: "xuě", translation: "снег", example: "下雪 [xià xuě] — идёт снег" },
    { id: 525, char: "颜色", pinyin: "yánsè", translation: "цвет; окраска", example: "给颜色看看 [gěi yánsè kànkàn] — проучить кого-либо" },
    { id: 526, char: "眼镜", pinyin: "yǎnjìng", translation: "очки", example: "" },
    { id: 527, char: "要求", pinyin: "yāoqiú", translation: "требовать; добиваться", example: "" },
    { id: 528, char: "爷爷", pinyin: "yéye", translation: "дедушка", example: "" },
    { id: 529, char: "一定", pinyin: "yīdìng", translation: "непременно, обязательно", example: "" },
    { id: 530, char: "一共", pinyin: "yīgòng", translation: "всего; итого", example: "" },
    { id: 531, char: "一会儿", pinyin: "yīhuìr", translation: "минутка; немного", example: "" },
    { id: 532, char: "一样", pinyin: "yīyàng", translation: "одинаковый; такой же", example: "" },
    { id: 533, char: "以后", pinyin: "yǐhòu", translation: "после; потом", example: "" },
    { id: 534, char: "以前", pinyin: "yǐqián", translation: "раньше, прежде", example: "" },
    { id: 535, char: "以为", pinyin: "yǐwéi", translation: "полагать, считать", example: "" },
    { id: 536, char: "一般", pinyin: "yībān", translation: "обычный, простой", example: "" },
    { id: 537, char: "一边", pinyin: "yībiān", translation: "одна сторона; с одной стороны", example: "他一边走一边想 [tā yībiān zǒu yībiān xiǎng] — он шёл и думал" },
    { id: 538, char: "一直", pinyin: "yīzhí", translation: "прямо; всё время", example: "" },
    { id: 539, char: "音乐", pinyin: "yīnyuè", translation: "музыка; музыкальный", example: "" },
    { id: 540, char: "银行", pinyin: "yínháng", translation: "банк; банковский", example: "" },
    { id: 541, char: "应该", pinyin: "yīnggāi", translation: "следует, должно", example: "" },
    { id: 542, char: "影响", pinyin: "yǐngxiǎng", translation: "влиять; оказывать влияние", example: "产生影响 [chǎnshēng yǐngxiǎng] — оказывать влияние" },
    { id: 543, char: "用", pinyin: "yòng", translation: "употреблять, использовать", example: "用武器 [yòng wǔqì] — применить оружие" },
    { id: 544, char: "游戏", pinyin: "yóuxì", translation: "игра, забава", example: "" },
    { id: 545, char: "有名", pinyin: "yǒumíng", translation: "известный, знаменитый", example: "" },
    { id: 546, char: "遇到", pinyin: "yùdào", translation: "встретить(ся); столкнуться", example: "" },
    { id: 547, char: "元", pinyin: "yuán", translation: "юань", example: "" },
    { id: 548, char: "愿意", pinyin: "yuànyì", translation: "желать; хотеть", example: "" },
    { id: 549, char: "月亮", pinyin: "yuèliang", translation: "луна; месяц", example: "" },
    { id: 550, char: "越", pinyin: "yuè", translation: "превысить", example: "越权 [yuèquán] — превысить права" },
    { id: 551, char: "云", pinyin: "yún", translation: "облако; туча", example: "" },
    { id: 552, char: "在", pinyin: "zài", translation: "быть в живых; находиться", example: "书在桌子上 [shū zài zhuōzi shang] — книга на столе" },
    { id: 553, char: "再", pinyin: "zài", translation: "снова; опять", example: "再说一遍 [zài shuō yī biàn] — сказать ещё раз" },
    { id: 554, char: "早上", pinyin: "zǎoshang", translation: "утром, спозаранку", example: "" },
    { id: 555, char: "站", pinyin: "zhàn", translation: "стоять; встать; станция", example: "站起来 [zhànqilai] — встать" },
    { id: 556, char: "张", pinyin: "zhāng", translation: "раскрывать; сч. сл. для листов", example: "" },
    { id: 557, char: "着急", pinyin: "zháojí", translation: "волноваться; беспокоиться", example: "" },
    { id: 558, char: "照顾", pinyin: "zhàogu", translation: "заботиться; ухаживать", example: "" },
    { id: 559, char: "照片", pinyin: "zhàopiàn", translation: "фотография", example: "" },
    { id: 560, char: "照相机", pinyin: "zhàoxiàngjī", translation: "фотоаппарат", example: "" },
    { id: 561, char: "着", pinyin: "zhe", translation: "глагольный суффикс продолженного вида", example: "他们开着会呢 [tāmen kāizhe huì ne] — они на собрании" },
    { id: 562, char: "真", pinyin: "zhēn", translation: "настоящий; истинный", example: "这是真事 [zhè shì zhēn shì] — это действительный факт" },
    { id: 563, char: "正在", pinyin: "zhèngzài", translation: "указывает на действие в данный момент", example: "事情正在好转 [shìqing zhèngzài hǎozhuǎn] — дела идут на поправку" },
    { id: 564, char: "只", pinyin: "zhǐ", translation: "только; лишь", example: "只剩下他一个人 [zhǐ shèngxià tā yīge rén] — остался только он один" },
    { id: 565, char: "中间", pinyin: "zhōngjiān", translation: "посередине; между", example: "中间派 [zhōngjiānpài] — промежуточные силы" },
    { id: 566, char: "终于", pinyin: "zhōngyú", translation: "в конечном счёте", example: "" },
    { id: 567, char: "种", pinyin: "zhǒng", translation: "семя; порода; род; вид", example: "各种树 [gèzhǒng shù] — различные деревья" },
    { id: 568, char: "重要", pinyin: "zhòngyào", translation: "важный", example: "重要性 [zhòngyàoxìng] — важность" },
    { id: 569, char: "周末", pinyin: "zhōumò", translation: "конец недели; уик-энд", example: "" },
    { id: 570, char: "主要", pinyin: "zhǔyào", translation: "главный; основной", example: "" },
    { id: 571, char: "祝", pinyin: "zhù", translation: "желать; поздравлять", example: "祝你健康 [zhù nǐ jiànkāng] — желаю вам здоровья" },
    { id: 572, char: "注意", pinyin: "zhùyì", translation: "обращать внимание", example: "注意力 [zhùyìlì] — внимательность" },
    { id: 573, char: "准备", pinyin: "zhǔnbèi", translation: "готовить; подготовка", example: "" },
    { id: 574, char: "字典", pinyin: "zìdiǎn", translation: "словарь", example: "" },
    { id: 575, char: "自己", pinyin: "zìjǐ", translation: "сам; себя", example: "自己人 [zìjǐrén] — свои люди" },
    { id: 576, char: "自行车", pinyin: "zìxíngchē", translation: "велосипед", example: "" },
    { id: 577, char: "总是", pinyin: "zǒngshì", translation: "всегда; всё время", example: "" },
    { id: 578, char: "走", pinyin: "zǒu", translation: "идти; ходить", example: "你走得太快 [nǐ zǒude tài kuài] — ты идёшь слишком быстро" },
    { id: 579, char: "最", pinyin: "zuì", translation: "самый; больше всего", example: "最多 [zuìduō] — больше всех" },
    { id: 580, char: "最近", pinyin: "zuìjìn", translation: "за последнее время; последний", example: "" },
    { id: 581, char: "左边", pinyin: "zuǒbian", translation: "левая сторона; налево", example: "" },
    { id: 582, char: "作业", pinyin: "zuòyè", translation: "работа; задание", example: "家庭作业 [jiātíng zuòyè] — домашняя работа" },
    { id: 583, char: "作用", pinyin: "zuòyòng", translation: "роль; значение", example: "起作用 [qǐ zuòyòng] — играть роль" },
    { id: 584, char: "啊", pinyin: "ā", translation: "междометие удивления", example: "啊, 是你! [ā, shì nǐ] — а, это ты!" },
    { id: 585, char: "爱情", pinyin: "ài qíng", translation: "любовь; чувство любви", example: "" },
    { id: 586, char: "安排", pinyin: "ān pái", translation: "налаживать; устраивать", example: "" },
    { id: 587, char: "安全", pinyin: "ān quán", translation: "безопасность; безопасный", example: "" },
    { id: 588, char: "暗", pinyin: "àn", translation: "тёмный; мрачный", example: "屋子太暗 [wūzi tài àn] — комната слишком тёмная" },
    { id: 589, char: "按时", pinyin: "àn shí", translation: "вовремя; своевременно", example: "" },
    { id: 590, char: "按照", pinyin: "àn zhào", translation: "согласно; по", example: "按照计划 [àn zhào jīhuà] — в соответствии с планом" },
    { id: 591, char: "包括", pinyin: "bāo kuò", translation: "охватывать, включать", example: "" },
    { id: 592, char: "保护", pinyin: "bǎo hù", translation: "защищать; охранять", example: "保护国家利益 [bǎohù guójiā lìyì] — защищать интересы страны" },
    { id: 593, char: "保证", pinyin: "bǎo zhèng", translation: "гарантировать; ручаться", example: "提出保证 [tíchū bǎozhèng] — предоставлять гарантии" },
    { id: 594, char: "抱", pinyin: "bào", translation: "обнимать", example: "抱孩子 [bào háizi] — нянчить ребёнка" },
    { id: 595, char: "抱歉", pinyin: "bào qiàn", translation: "сожалеть, выражать сожаление", example: "" },
    { id: 596, char: "报道", pinyin: "bào dào", translation: "сообщать, информировать", example: "据新华社报道 [jù xīnhuáshè bàodào] — по сообщениям агентства Синьхуа" },
    { id: 597, char: "报名", pinyin: "bào míng", translation: "записаться, зарегистрироваться", example: "" },
    { id: 598, char: "倍", pinyin: "bèi", translation: "раз; крат", example: "超过一倍 [chāoguò yībèi] — превзойти в 2 раза" },
    { id: 599, char: "本来", pinyin: "běn lái", translation: "первоначальный; вообще говоря", example: "" },
    { id: 600, char: "笨", pinyin: "bèn", translation: "глупый; тупой", example: "他很笨 [tā hěn bèn] — он очень тупой" }
];