// Массив 150 НОВЫХ слов для HSK 2 (слов, которых нет в HSK 1)
const hsk2NewWords = [
    { id: 151, char: "吧", pinyin: "ba", translation: "выражает побуждение или предположение", example: "你放心吧 [nǐ fàngxīn ba] — успокойся; не беспокойся" },
    { id: 152, char: "白", pinyin: "bái", translation: "белый; седой", example: "白衣服 [bái yīfu] — белое платье; 白头发 [bái tóufa] — седые волосы" },
    { id: 153, char: "百", pinyin: "bǎi", translation: "сто; сотня", example: "" },
    { id: 154, char: "帮助", pinyin: "bāngzhù", translation: "помогать; помощь", example: "" },
    { id: 155, char: "报纸", pinyin: "bàozhǐ", translation: "газета; газеты", example: "" },
    { id: 156, char: "比", pinyin: "bǐ", translation: "сравнивать; в сравнении", example: "比力气 [bǐ lìqì] — помериться силами; 他比我高 [tā bǐ wǒ gāo] — он выше меня ростом" },
    { id: 157, char: "别", pinyin: "bié", translation: "расставаться, разлучаться не нужно; нечего; не", example: "别家 [biéjiā] — расстаться с семьёй; 别动 ! [bié dòng] — не двигаться!, ни с места!" },
    { id: 158, char: "不客气", pinyin: "bùkěqi", translation: "не церемоньтесь!; не стесняйтесь!", example: "" },
    { id: 159, char: "长", pinyin: "cháng", translation: "длинный; длительный, долгий", example: "路很长 [lù hěn cháng] — дорога очень длинная; 很长的过程 [hěn chángde guòchéng] — очень длительный процесс" },
    { id: 160, char: "唱歌", pinyin: "chànggē", translation: "петь; пение", example: "" },
    { id: 161, char: "出", pinyin: "chū", translation: "выходить; выезжать; превышать", example: "出房间 [chū fángjiān] — выйти из комнаты; 不出三个月 [bùchū sānge yuè] — не более трёх месяцев" },
    { id: 162, char: "穿", pinyin: "chuān", translation: "пронзить; пробить; одевать; надевать", example: "穿个洞 [chuānge dòng] — проделать дыру; 穿衣服 [chuān yīfu] — одеваться; носить одежду [костюм]" },
    { id: 163, char: "船", pinyin: "chuán", translation: "судно, корабль; пароход; лодка", example: "渔船 [yúchuán] — рыболовное судно; 帆船 [fānchuán] — парусник" },
    { id: 164, char: "次", pinyin: "cì", translation: "следующий; второй; раз", example: "次日 [cìrì] — на следующий [другой] день; 一天三次 [yītiān sāncì] — три раза в день" },
    { id: 165, char: "从", pinyin: "cóng", translation: "из; от; с", example: "从上到下 [cóng shàng dào xià] — сверху донизу; 从莫斯科到北京 [cóng mòsīkē dào běijīng] — от Москвы до Пекина" },
    { id: 166, char: "错", pinyin: "cuò", translation: "неправильный; ошибочный; ошибаться; ошибочно", example: "我错了 [wǒ cuòle] — я ошибся; 说错 [shuōcuò] — сказать неправильно; оговориться" },
    { id: 167, char: "打篮球", pinyin: "dǎlánqiú", translation: "играть в баскетбол", example: "" },
    { id: 168, char: "大家", pinyin: "dàjiā", translation: "все; все вместе", example: "" },
    { id: 169, char: "但是", pinyin: "dànshì", translation: "но; однако; тем не менее", example: "" },
    { id: 170, char: "到", pinyin: "dào", translation: "достигать; прибывать; до", example: "火车到了 [huǐchē dàole] — поезд прибыл; 到半夜 [dào bànyè] — до полуночи; к полуночи" },
    { id: 171, char: "得", pinyin: "de", translation: "показатель обстоятельства, следующего за сказуемым", example: "他跑得快 [tā pǎode kuài] — он бежит быстро" },
    { id: 172, char: "等", pinyin: "děng", translation: "ожидать, ждать", example: "你等一会 [nǐ děng yīhuì] — подожди немножко" },
    { id: 173, char: "弟弟", pinyin: "dìdi", translation: "младший брат", example: "" },
    { id: 174, char: "第一", pinyin: "dìyī", translation: "первый; во-первых; первейший; номер один", example: "第一把手 [dìyībǎshǒu] — глава; начальник; первое лицо; 第一手 [dìyīshǒu] — из первых рук" },
    { id: 175, char: "对", pinyin: "duì", translation: "пара; правильный, верный; правильно!, верно!", example: "对夫妇 [yīduì fūfù] — супружеская пара; 作得对 [zuòde duì] — сделано правильно" },
    { id: 176, char: "懂", pinyin: "dǒng", translation: "понять, уразуметь", example: "你懂了没有 ? [nǐ dǒngle méiyǒu] — Вы поняли? 你懂什么 ! [nǐ dǒng shénme] — Ничего вы не понимаете!" },
    { id: 177, char: "房间", pinyin: "fángjiān", translation: "комната; номер", example: "" },
    { id: 178, char: "非常", pinyin: "fēicháng", translation: "чрезвычайный; необыкновенный", example: "非常会议 [fēicháng huìyì] — чрезвычайная сессия" },
    { id: 179, char: "服务员", pinyin: "fúwùyuán", translation: "обслуживающий персонал; официант", example: "" },
    { id: 180, char: "高", pinyin: "gāo", translation: "высокий; высший (об образовании)", example: "他比我高 [tā bǐ wǒ gāo] — он выше меня; 高年级 [gāo niánjí] — старшие классы [курсы]" },
    { id: 181, char: "告诉", pinyin: "gàosu", translation: "сказать; сообщить", example: "" },
    { id: 182, char: "哥哥", pinyin: "gēge", translation: "старший брат", example: "" },
    { id: 183, char: "给", pinyin: "gěi", translation: "давать; предоставлять", example: "他给我一本书 [tā gěi wǒ yīběn shū] — он дал мне книгу; 给孩子讲个故事 [gěi háizi jiǎngge gùshi] — рассказать ребёнку сказку" },
    { id: 184, char: "公共汽车", pinyin: "gōnggòng qìchē", translation: "автобус", example: "" },
    { id: 185, char: "公斤", pinyin: "gōngjīn", translation: "килограмм", example: "" },
    { id: 186, char: "公司", pinyin: "gōngsī", translation: "компания; фирма", example: "" },
    { id: 187, char: "贵", pinyin: "guì", translation: "дорогой; ценный", example: "东西又好又不贵 [dōngxi yòu hǎo yòu bùguì] — вещь и хорошая и недорогая; 创作贵精不贵多 [chuàngzuò guì jǐng bùguì duō] — в творчестве важно качество, а не количество; творчество ценно качеством, а не количеством" },
    { id: 188, char: "过", pinyin: "guō", translation: "проходить через; переходить; пересекать; отмечать; справлять (о праздниках)", example: "过街 [guòjiē] — переходить через улицу; 过生日 [guò shēngrì] — отмечать [справлять] день рождения" },
    { id: 189, char: "还", pinyin: "hái", translation: "ещё; всё ещё", example: "还早 [háizǎo] — ещё рано; 今天比昨天还冷 [jīntiān bǐ zuótiān hái lěng] — сегодня ещё холоднее чем вчера" },
    { id: 190, char: "孩子", pinyin: "háizi", translation: "ребёнок, дитя", example: "" },
    { id: 191, char: "好吃", pinyin: "hǎochī", translation: "вкусный", example: "" },
    { id: 192, char: "号", pinyin: "hào", translation: "название; размер; число (месяца)", example: "店号 [diànhào] — название магазина; 大号 [dàhào] — большой размер; большого размера" },
    { id: 193, char: "黑", pinyin: "hēi", translation: "чёрный; тёмный; мрачный", example: "黑头发 [hēi tóufa] — чёрные волосы; 天黑了 [tiān hēile] — стемнело" },
    { id: 194, char: "红", pinyin: "hóng", translation: "красный, алый", example: "红旗 [hóngqí] — красное знамя" },
    { id: 195, char: "欢迎", pinyin: "huānyíng", translation: "приветствовать; встречать", example: "欢迎词 [huānyíngcí] — приветственная речь; приветствие; 致欢迎词 [zhì huānyíngcí] — обратиться с приветствием" },
    { id: 196, char: "回答", pinyin: "huídá", translation: "отвечать; ответ", example: "" },
    { id: 197, char: "鸡蛋", pinyin: "jīdàn", translation: "куриное яйцо", example: "" },
    { id: 198, char: "件", pinyin: "jiàn", translation: "сч. сл. для предметов одежды, дел, вещей, документов", example: "两件事 [liǎngjiàn shì] — два дела; 件工作 [yījiàn gōngzuò] — (одна) работа" },
    { id: 199, char: "教室", pinyin: "jiàoshì", translation: "класс; аудитория", example: "" },
    { id: 200, char: "姐姐", pinyin: "jiějie", translation: "старшая сестра; в обращении сестрица", example: "" },
    { id: 201, char: "介绍", pinyin: "jièshào", translation: "рекомендовать; знакомить, представлять", example: "介绍信 [jièshàoxìn] — рекомендательное письмо; рекомендация" },
    { id: 202, char: "进", pinyin: "jìn", translation: "идти [продвигаться] вперёд; входить", example: "南进 [nánjìn] — двигаться на юг; 进屋子 [jìn wūzi] — войти в комнату" },
    { id: 203, char: "近", pinyin: "jìn", translation: "близкий, вблизи; рядом", example: "我住得很近 [wǒ zhùde hěn jìn] — я живу очень близко" },
    { id: 204, char: "就", pinyin: "jiù", translation: "именно, как раз; сейчас же, немедленно; тогда; то; в таком случае", example: "就在这里 [jiù zài zhèli] — как раз здесь; 我就回来 [wǒ jiù huílai] — я сейчас же вернусь; 想起来就说 [xiǎngqilai jiù shuō] — когда вспомнишь, (то) скажи" },
    { id: 205, char: "觉得", pinyin: "juéde", translation: "чувствовать, ощущать; сознавать", example: "我觉得 [wǒ juéde] — мне кажется; я думаю; по-моему" },
    { id: 206, char: "咖啡", pinyin: "kāfēi", translation: "кофе", example: "清咖啡 [qīng kāfēi] — чёрный кофе; 牛奶咖啡 [niúnǎi kāfēi] — кофе с молоком" },
    { id: 207, char: "开始", pinyin: "kāishǐ", translation: "начинать; начало", example: "" },
    { id: 208, char: "考试", pinyin: "kǎoshì", translation: "экзамен; экзамены", example: "экзамен; экзамены 毕业考试 [bìyè kǎoshì] — выпускные экзамены; 进行考试 [jìnxíng kǎoshì] — проводить экзамены" },
    { id: 209, char: "可能", pinyin: "kěnéng", translation: "возможно; вероятно", example: "资产阶级领导的东西不可能属于人民大衆 то, что находится под руководством буржуазии, не может относиться к (принадлежать) народным массам" },
    { id: 210, char: "可以", pinyin: "kěyǐ", translation: "можно, возможно; дозволено, разрешается", example: "" },
    { id: 211, char: "课", pinyin: "kè", translation: "урок; занятия; предмет", example: "上课 [shàngkè] — идти на занятия; 俄语课 [éyǔkè] — урок русского языка" },
    { id: 212, char: "快", pinyin: "kuài", translation: "быстрый, скорый; радостный, весёлый", example: "他快回来 [tā kuài huílái] — он скоро вернётся; 快些 [kuàixiē] — побыстрее!" },
    { id: 213, char: "快乐", pinyin: "kuàilè", translation: "весёлый; радостный; весело", example: "" },
    { id: 214, char: "累", pinyin: "lèi", translation: "уставать; утомлять(ся)", example: "我累了 [wǒ lèile] — я устал" },
    { id: 215, char: "离", pinyin: "lí", translation: "отстоять от; от; покидать", example: "车站离这儿不远 [chēzhàn lí zhèr bùyuǎn] — станция [остановка] находится недалеко отсюда; 他始终没离会场 [tā shǐzhōng méi lí huìchǎng] — он до самого конца не покидал зала заседаний" },
    { id: 216, char: "两", pinyin: "liǎng", translation: "два; пара; оба", example: "两本书 [liǎngběn shū] — две книги" },
    { id: 217, char: "路", pinyin: "lù", translation: "дорога; путь; улица", example: "山路 [shānlù] — горная дорога" },
    { id: 218, char: "旅游", pinyin: "lǚyóu", translation: "туризм; туристический", example: "旅游游车 [lǚyóuchē] — туристический автобус" },
    { id: 219, char: "卖", pinyin: "mài", translation: "продавать; торговать", example: "卖一批货 [mài yī pī huò] — продать партию товара" },
    { id: 220, char: "慢", pinyin: "màn", translation: "медленный; медлить; отставать", example: "树长得慢 [shù zhǎngde màn] — деревья растут медленно; 表慢两分钟 [biǎo màn liǎngfēnzhōng] — часы отстают на две минуты" },
    { id: 221, char: "忙", pinyin: "máng", translation: "быть занятым; хлопотать", example: "工作忙 [gōngzuò máng] — много работы; 这几天我很忙 [zhè jǐtiān wǒ hěn máng] — эти дни я очень занят" },
    { id: 222, char: "每", pinyin: "měi", translation: "каждый, всякий", example: "每次 [měicì] — каждый раз; 每天 [měitiān] — каждый день, ежедневно; 每个人 [měige rén] — каждый человек" },
    { id: 223, char: "妹妹", pinyin: "mèimei", translation: "младшая сестра", example: "" },
    { id: 224, char: "门", pinyin: "mén", translation: "дверь; ворота; вход", example: "开门 [kāi mén] — открыть дверь [ворота]" },
    { id: 225, char: "男人", pinyin: "nánrén", translation: "мужчина", example: "" },
    { id: 226, char: "您", pinyin: "nín", translation: "Вы, Ваш", example: "" },
    { id: 227, char: "牛奶", pinyin: "niúnǎi", translation: "молоко; молочный", example: "" },
    { id: 228, char: "女人", pinyin: "nǚrén", translation: "женщина", example: "女人裸体画 жив. ню (изображение обнажённого женского тела)" },
    { id: 229, char: "旁边", pinyin: "pángbiān", translation: "сбоку; рядом; около", example: "" },
    { id: 230, char: "跑步", pinyin: "pǎobù", translation: "бег", example: "跑步走 ! [pǎobù zǒu] — бегом, марш!" },
    { id: 231, char: "便宜", pinyin: "piányi", translation: "дешёвый", example: "" },
    { id: 232, char: "票", pinyin: "piào", translation: "билет; талон; квитанция", example: "电车票 [diànchēpiào] — трамвайный билет" },
    { id: 233, char: "妻子", pinyin: "qīzi", translation: "жена", example: "" },
    { id: 234, char: "起床", pinyin: "qǐchuáng", translation: "встать с постели", example: "" },
    { id: 235, char: "千", pinyin: "qiān", translation: "тысяча; кило-", example: "千卡 [qiānkǎ] — килокалория" },
    { id: 236, char: "晴", pinyin: "qíng", translation: "ясный, безоблачный; проясниться", example: "天晴了 [tiān qíngle] — (небо) прояснилось; 晴空 [qíngkōng] — чистое [безоблачное] небо" },
    { id: 237, char: "去年", pinyin: "qùnián", translation: "прошлый год", example: "" },
    { id: 238, char: "让", pinyin: "ràng", translation: "заставлять; позволять; разрешать; уступать", example: "不要让人等你 [bùyào ràng rén děng nǐ] — не заставляйте людей ждать вас; 让我想一想 [ràng wǒ xiǎngyīxiǎng] — разрешите мне подумать" },
    { id: 239, char: "上班", pinyin: "shàngbān", translation: "идти на работу; заступить на смену", example: "" },
    { id: 240, char: "身体", pinyin: "shēntǐ", translation: "тело; телосложение; здоровье", example: "他身体很好 [tā shēntǐ hěn hǎo] — у него очень хорошее здоровье" },
    { id: 241, char: "生病", pinyin: "shēngbìng", translation: "заболеть", example: "" },
    { id: 242, char: "生日", pinyin: "shēngrì", translation: "день рождения", example: "" },
    { id: 243, char: "时间", pinyin: "shíjiān", translation: "время; промежуток времени", example: "没有时间 [méiyǒu shíjiān] — нет времени; некогда" },
    { id: 244, char: "事情", pinyin: "shìqing", translation: "дело, событие, инцидент; случай, факт", example: "" },
    { id: 245, char: "手表", pinyin: "shǒubiǎo", translation: "наручные часы", example: "" },
    { id: 246, char: "手机", pinyin: "shǒujī", translation: "Мобильный (сотовый) телефон", example: "" },
    { id: 247, char: "送", pinyin: "sòng", translation: "посылать; дарить; провожать", example: "送报 [sòngbào] — доставлять газеты; 送礼物 [sòng lǐwù] — преподнести подарок; 送客 [sòngkè] — провожать гостей" },
    { id: 248, char: "所以", pinyin: "suǒyǐ", translation: "потому; таким образом", example: "" },
    { id: 249, char: "它", pinyin: "tā", translation: "оно; она; он", example: "" },
    { id: 250, char: "踢足球", pinyin: "tī zúqiú", translation: "играть в футбол", example: "" },
    { id: 251, char: "题", pinyin: "tí", translation: "тема; вопрос; проблема", example: "话题 [huàtí] — тема разговора 考题 [kǎotí] — экзаменационные вопросы; 讨论题 [tǎolùntí] — тема дискуссии" },
    { id: 252, char: "天气", pinyin: "tiānqì", translation: "погода; климат", example: "天气预报 [tiānqì yùbào] — прогноз погоды" },
    { id: 253, char: "跳舞", pinyin: "tiàowǔ", translation: "танцевать; плясать", example: "" },
    { id: 254, char: "听报告", pinyin: "tīng bàogào", translation: "слушать доклад", example: "" },
    { id: 255, char: "外", pinyin: "wài", translation: "внешний, наружный; снаружи; вне; за", example: "国外 [guówài] — за границей; 往外走 [wǎng wài zǒu] — выйти наружу" },
    { id: 256, char: "完", pinyin: "wán", translation: "закончить, завершить; кончиться", example: "时间完了 [shíjiān wánle] — время истекло; 用完 [yòngwán] — до конца использовать [израсходовать]" },
    { id: 257, char: "玩", pinyin: "wán", translation: "играть; забавляться; гулять; развлекаться", example: "玩球 [wán qiú] — играть в мяч; 出去玩 [chūqu wán] — выйти погулять" },
    { id: 258, char: "晚上", pinyin: "wǎnshang", translation: "вечером; вечер", example: "" },
    { id: 259, char: "喂鸡", pinyin: "wèi jī", translation: "кормить кур", example: "" },
    { id: 260, char: "为什么", pinyin: "wèishénme", translation: "почему; отчего; зачем", example: "" },
    { id: 261, char: "问", pinyin: "wèn", translation: "спрашивать; справляться о чём-либо", example: "问路 [wèn lù] — спрашивать дорогу; 问一个问题 [wèn yīge wèntí] — задать вопрос" },
    { id: 262, char: "问题", pinyin: "wèntí", translation: "вопрос; проблема; тема", example: "提问题 [tí wèntí] — задать вопрос" },
    { id: 263, char: "西瓜", pinyin: "xīguā", translation: "арбуз", example: "" },
    { id: 264, char: "希望", pinyin: "xīwàng", translation: "надеяться; надежда", example: "" },
    { id: 265, char: "洗", pinyin: "xǐ", translation: "мыть; стирать; купать; умывать", example: "洗手 [xǐshǒu] — мыть руки; 洗衣服 [xǐ yīfu] — стирать бельё" },
    { id: 266, char: "向", pinyin: "xiàng", translation: "быть обращённым к; направление; курс", example: "窗子向南 [chuángzi xiàng nán] — окна выходят на юг; 向朋友借钱 [xiàng péngyou jièqián] — взять в долг у приятеля" },
    { id: 267, char: "小时", pinyin: "xiǎoshí", translation: "час", example: "" },
    { id: 268, char: "笑", pinyin: "xiào", translation: "смеяться; смех; улыбаться; улыбка", example: "他笑起来了 [tā xiàoqilaile] — он рассмеялся; 大笑 [dàxiào] — громко рассмеяться; 傻笑 [shǎxiào] — глупая улыбка" },
    { id: 269, char: "新", pinyin: "xīn", translation: "новый; современный; свежий", example: "新书 [xīnshū] — новая книга" },
    { id: 270, char: "姓", pinyin: "xìng", translation: "фамилия; по фамилии", example: "你姓什么 ? [nǐ xìng shénme] — как ваша фамилия? 姓王的 [xìng wáng de] — человек по фамилии Ван" },
    { id: 271, char: "休息", pinyin: "xiūxi", translation: "отдыхать; отдых; перерыв; антракт", example: "" },
    { id: 272, char: "雪", pinyin: "xuě", translation: "снег", example: "下雪 [xià xuě] — идёт снег" },
    { id: 273, char: "颜色", pinyin: "yánsè", translation: "цвет; окраска", example: "给 … 颜色看看 [gěi... yánsè kànkàn] — проучить кого-либо" },
    { id: 274, char: "眼睛", pinyin: "yǎnjing", translation: "глаза", example: "" },
    { id: 275, char: "羊肉", pinyin: "yángròu", translation: "баранина", example: "" },
    { id: 276, char: "药", pinyin: "yào", translation: "лекарство; медикаменты; лекарственный", example: "服药 [fú yào] — принимать лекарство" },
    { id: 277, char: "要", pinyin: "yào", translation: "хотеть, желать; нужно, необходимо; просить; требовать", example: "我要去看电影 [wǒ yào qù kàn diànyǐng] — я хочу пойти в кино" },
    { id: 278, char: "也", pinyin: "yě", translation: "тоже, также; и", example: "我也去 [wǒ yě qù] — я тоже пойду" },
    { id: 279, char: "已经", pinyin: "yǐjīng", translation: "уже", example: "" },
    { id: 280, char: "一起", pinyin: "yīqǐ", translation: "вместе; совместно; сообща", example: "" },
    { id: 281, char: "意思", pinyin: "yìsi", translation: "мысль; идея; смысл, значение; интерес", example: "很有意思 [hěn yǒu yìsi] — очень интересно [занятно]" },
    { id: 282, char: "阴", pinyin: "yīn", translation: "«инь» (женское начало в древней китайской философии); тёмный; пасмурный; тень", example: "阴天 [yīntiān] — пасмурный день; пасмурная погода; 树阴 [shùyīn] — тень от дерева" },
    { id: 283, char: "因为", pinyin: "yīnwèi", translation: "так как, потому что; вследствие того, что; ибо", example: "因为 … 关系 [yīnwèi... guānxi] — по… обстоятельствам; принимая во внимание…; 因为家庭关系 [yīnwèi jiātíng guānxi] — по семейным обстоятельствам" },
    { id: 284, char: "游泳", pinyin: "yóuyǒng", translation: "плавать; плавание", example: "游泳衣 [yóuyǒngyī] — купальник" },
    { id: 285, char: "右边", pinyin: "yòubian", translation: "правая сторона; справа; правый", example: "" },
    { id: 286, char: "鱼", pinyin: "yú", translation: "рыба; рыбный; рыбий", example: "打鱼 [dǎ yú] — ловить рыбу; 鱼汤 [yútāng] — рыбный суп; уха" },
    { id: 287, char: "元", pinyin: "yuán", translation: "юань", example: "" },
    { id: 288, char: "远", pinyin: "yuǎn", translation: "далёкий; дальний; далеко", example: "他住得很远 [tā zhùde hěn yuǎn] — он живёт очень далеко" },
    { id: 289, char: "运动", pinyin: "yùndòng", translation: "спорт; атлетика; спортивный", example: "田径运动 [tiánjìng yùndòng] — лёгкая атлетика; 运动服 [yùndòngfú] — спортивный костюм" },
    { id: 290, char: "再", pinyin: "zài", translation: "снова; опять; ещё", example: "再说一遍 [zài shuō yī biàn] — сказать ещё раз; повторить" },
    { id: 291, char: "早上", pinyin: "zǎoshang", translation: "утром, спозаранку", example: "" },
    { id: 292, char: "张", pinyin: "zhāng", translation: "раскрывать; открывать; сч. сл. для листов, столов, кроватей", example: "" },
    { id: 293, char: "丈夫", pinyin: "zhàngfū", translation: "муж; настоящий мужчина", example: "" },
    { id: 294, char: "找", pinyin: "zhǎo", translation: "искать; разыскивать; отыскивать", example: "你找什么东西 [nǐ zhǎo shénme dōngxi] — что вы ищете?" },
    { id: 295, char: "着", pinyin: "zhe", translation: "глагольный суффикс, указывающий на продолженный характер действия или состояния", example: "他们开着会呢 [tāmen kāizhe huì ne] — они на собрании; 墙上挂着一幅画 [qiáng shang guàzhe yī fú huà] — на стене висит картина" },
    { id: 296, char: "真", pinyin: "zhēn", translation: "настоящий; истинный; подлинный; достоверный; действительный", example: "这是真事 [zhè shì zhēn shì] — это действительный факт; 真面目 [zhēn miànmù] — истинное [подлинное] лицо; истинный облик" },
    { id: 297, char: "正在", pinyin: "zhèngzài", translation: "перед глаголом указывает на то, что действие происходит в данный момент", example: "事情正在好转 [shìqing zhèngzài hǎozhuǎn] — дела идут на поправку; 温度正在慢慢上升 [wēndù zhèngzài mànmàn shàngshēng] — температура постепенно поднимается" },
    { id: 298, char: "知道", pinyin: "zhīdao", translation: "знать; иметь представление", example: "" },
    { id: 299, char: "住", pinyin: "zhù", translation: "жить, проживать", example: "我家住在城外 [wǒ jiā zhù zài chéng wài] — моя семья живёт за городом; 记住 [jìzhù] — запомнить; 站住 ! [zhànzhù] — стой! (команда)" },
    { id: 300, char: "准备", pinyin: "zhǔnbèi", translation: "готовить; подготавливать; быть готовым; подготовка", example: "" }
];